.class public Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements Ljava/io/Serializable;


# static fields
.field public static final serialVersionUID:J = 0xd6f0c97cbc6e02dL


# instance fields
.field public final autoAddIntParams:I

.field public final enableSloHttpHeaderLogging:Z

.field public final grootPrefetchSuboriginBlocklist:Ljava/lang/String;

.field public final maxAllowed503RetryCount:I


# direct methods
.method public constructor <init>(LX/Eo1;)V
    .locals 1

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/16 v0, 0x65

    iput v0, p0, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;->autoAddIntParams:I

    const/4 v0, -0x1

    iput v0, p0, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;->maxAllowed503RetryCount:I

    const/4 v0, 0x0

    iput-boolean v0, p0, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;->enableSloHttpHeaderLogging:Z

    const-string v0, ""

    iput-object v0, p0, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;->grootPrefetchSuboriginBlocklist:Ljava/lang/String;

    return-void
.end method

.method public synthetic constructor <init>(LX/Eo1;LX/Ee1;)V
    .locals 0

    invoke-direct {p0, p1}, Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;-><init>(LX/Eo1;)V

    return-void
.end method
