.class public LX/FBk;
.super Ljava/lang/Object;
.source ""


# instance fields
.field public A00:I

.field public A01:I

.field public A02:I

.field public A03:I

.field public A04:I

.field public A05:I

.field public A06:I

.field public A07:I

.field public A08:I

.field public A09:I

.field public A0A:I

.field public A0B:I

.field public A0C:I

.field public A0D:I

.field public A0E:I

.field public A0F:I

.field public A0G:J

.field public A0H:LX/GRG;

.field public A0I:LX/GRG;

.field public A0J:LX/GRL;

.field public A0K:LX/GRj;

.field public A0L:LX/K6x;

.field public A0M:LX/GRC;

.field public A0N:LX/GRK;

.field public A0O:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

.field public A0P:LX/GRV;

.field public A0Q:LX/GRH;

.field public A0R:LX/GRA;

.field public A0S:LX/GRY;

.field public A0T:LX/GRY;

.field public A0U:LX/GRF;

.field public A0V:Ljava/lang/String;

.field public A0W:Ljava/util/HashMap;

.field public A0X:Ljava/util/Map;

.field public A0Y:Ljava/util/Set;

.field public A0Z:Ljava/util/Set;

.field public A0a:Ljava/util/Set;

.field public A0b:Ljava/util/Set;

.field public A0c:Ljava/util/Set;

.field public A0d:Ljava/util/Set;

.field public A0e:Z

.field public A0f:Z

.field public A0g:Z

.field public A0h:Z

.field public A0i:Z

.field public A0j:Z

.field public A0k:Z

.field public A0l:Z

.field public A0m:Z


# direct methods
.method public constructor <init>()V
    .locals 6

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v2, 0x0

    sget-object v0, LX/GRl;->A00:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-object v0, p0, LX/FBk;->A0O:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

    const/4 v1, 0x1

    iput-boolean v2, p0, LX/FBk;->A0f:Z

    const/4 v0, 0x3

    iput v0, p0, LX/FBk;->A07:I

    const/16 v4, 0x7d0

    const-string v0, "ExoService"

    iput-object v0, p0, LX/FBk;->A0V:Ljava/lang/String;

    iput-boolean v1, p0, LX/FBk;->A0l:Z

    new-instance v0, LX/Ezu;

    invoke-direct {v0}, LX/Ezu;-><init>()V

    iget-boolean v1, v0, LX/Ezu;->A00:Z

    new-instance v0, LX/GRK;

    invoke-direct {v0, v1}, LX/GRK;-><init>(Z)V

    iput-object v0, p0, LX/FBk;->A0N:LX/GRK;

    const/16 v3, 0x3e8

    const/16 v5, 0x1f4

    new-instance v0, LX/GRY;

    invoke-direct {v0, v5, v4}, LX/GRY;-><init>(II)V

    iput-object v0, p0, LX/FBk;->A0S:LX/GRY;

    new-instance v0, LX/GRY;

    invoke-direct {v0, v2, v2}, LX/GRY;-><init>(II)V

    iput-object v0, p0, LX/FBk;->A0T:LX/GRY;

    new-instance v0, LX/GRV;

    invoke-direct {v0}, LX/GRV;-><init>()V

    iput-object v0, p0, LX/FBk;->A0P:LX/GRV;

    new-instance v0, LX/K6x;

    invoke-direct {v0}, LX/K6x;-><init>()V

    iput-object v0, p0, LX/FBk;->A0L:LX/K6x;

    sget-object v0, LX/GRj;->A00:LX/GRj;

    iput-object v0, p0, LX/FBk;->A0K:LX/GRj;

    new-instance v0, LX/GRL;

    invoke-direct {v0}, LX/GRL;-><init>()V

    iput-object v0, p0, LX/FBk;->A0J:LX/GRL;

    new-instance v0, LX/GRC;

    invoke-direct {v0}, LX/GRC;-><init>()V

    iput-object v0, p0, LX/FBk;->A0M:LX/GRC;

    new-instance v0, LX/GRF;

    invoke-direct {v0}, LX/GRF;-><init>()V

    iput-object v0, p0, LX/FBk;->A0U:LX/GRF;

    new-instance v0, LX/GRA;

    invoke-direct {v0}, LX/GRA;-><init>()V

    iput-object v0, p0, LX/FBk;->A0R:LX/GRA;

    new-instance v1, LX/F7m;

    invoke-direct {v1}, Ljava/lang/Object;-><init>()V

    const v0, 0x186a0

    iput v0, v1, LX/F7m;->A00:I

    iput v3, v1, LX/F7m;->A03:I

    iput v5, v1, LX/F7m;->A02:I

    const/16 v0, 0xfa

    iput v0, v1, LX/F7m;->A01:I

    new-instance v0, LX/GRG;

    invoke-direct {v0, v1}, LX/GRG;-><init>(LX/F7m;)V

    iput-object v0, p0, LX/FBk;->A0H:LX/GRG;

    new-instance v1, LX/F7m;

    invoke-direct {v1}, Ljava/lang/Object;-><init>()V

    iput v4, v1, LX/F7m;->A00:I

    const v0, 0x249f0

    iput v0, v1, LX/F7m;->A03:I

    const v0, 0x86470

    iput v0, v1, LX/F7m;->A02:I

    const v0, 0x1e8480

    iput v0, v1, LX/F7m;->A01:I

    new-instance v0, LX/GRG;

    invoke-direct {v0, v1}, LX/GRG;-><init>(LX/F7m;)V

    iput-object v0, p0, LX/FBk;->A0I:LX/GRG;

    iput-boolean v2, p0, LX/FBk;->A0g:Z

    iput-boolean v2, p0, LX/FBk;->A0i:Z

    const/16 v4, 0xfa0

    invoke-static {}, LX/1ac;->A1A()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/FBk;->A0W:Ljava/util/HashMap;

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/FBk;->A0G:J

    invoke-static {}, LX/1ac;->A1A()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/FBk;->A0X:Ljava/util/Map;

    const/16 v0, 0x7530

    iput v0, p0, LX/FBk;->A04:I

    const/4 v1, -0x1

    iput v1, p0, LX/FBk;->A0D:I

    iput v4, p0, LX/FBk;->A03:I

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FBk;->A0b:Ljava/util/Set;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FBk;->A0a:Ljava/util/Set;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FBk;->A0c:Ljava/util/Set;

    new-instance v0, LX/GRH;

    invoke-direct {v0}, LX/GRH;-><init>()V

    iput-object v0, p0, LX/FBk;->A0Q:LX/GRH;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FBk;->A0Z:Ljava/util/Set;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FBk;->A0Y:Ljava/util/Set;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FBk;->A0d:Ljava/util/Set;

    const/16 v0, 0x28

    iput v0, p0, LX/FBk;->A0C:I

    iput v0, p0, LX/FBk;->A0B:I

    iput v2, p0, LX/FBk;->A08:I

    iput v1, p0, LX/FBk;->A09:I

    iput v1, p0, LX/FBk;->A0E:I

    iput v3, p0, LX/FBk;->A06:I

    const/16 v0, 0x7d0

    iput v0, p0, LX/FBk;->A05:I

    iput v3, p0, LX/FBk;->A00:I

    iput v3, p0, LX/FBk;->A02:I

    const v0, 0x8000

    iput v0, p0, LX/FBk;->A01:I

    iput-boolean v2, p0, LX/FBk;->A0h:Z

    iput-boolean v2, p0, LX/FBk;->A0e:Z

    const/16 v0, 0x18

    iput v0, p0, LX/FBk;->A0A:I

    iput-boolean v2, p0, LX/FBk;->A0m:Z

    iput v1, p0, LX/FBk;->A0F:I

    return-void
.end method
