.class public interface abstract annotation Lcom/facebook/ultralight/AutoGeneratedSwitchSubClassMasterMethod;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements Ljava/lang/annotation/Annotation;
