.class public final LX/FU8;
.super Ljava/lang/Object;
.source ""


# static fields
.field public static final A0m:Ljava/util/HashSet;


# instance fields
.field public A00:I

.field public A01:I

.field public A02:I

.field public A03:I

.field public A04:I

.field public A05:J

.field public A06:LX/GRI;

.field public A07:LX/GRI;

.field public A08:LX/Dwr;

.field public A09:LX/GRO;

.field public A0A:LX/GR9;

.field public A0B:LX/GRf;

.field public A0C:LX/K6w;

.field public A0D:LX/GRB;

.field public A0E:LX/GRX;

.field public A0F:LX/GRP;

.field public A0G:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

.field public A0H:LX/GRQ;

.field public A0I:LX/GRW;

.field public A0J:LX/GRM;

.field public A0K:LX/GRZ;

.field public A0L:LX/GRZ;

.field public A0M:LX/GRE;

.field public A0N:Ljava/lang/String;

.field public A0O:Ljava/util/HashSet;

.field public A0P:Ljava/util/Map;

.field public A0Q:Ljava/util/Set;

.field public A0R:Ljava/util/Set;

.field public A0S:Ljava/util/Set;

.field public A0T:Ljava/util/Set;

.field public A0U:Ljava/util/Set;

.field public A0V:Ljava/util/Set;

.field public A0W:Ljava/util/Set;

.field public A0X:Ljava/util/Set;

.field public A0Y:Z

.field public A0Z:Z

.field public A0a:Z

.field public A0b:Z

.field public A0c:Z

.field public A0d:Z

.field public A0e:Z

.field public A0f:Z

.field public A0g:Z

.field public A0h:Z

.field public A0i:Z

.field public A0j:Z

.field public A0k:Z

.field public A0l:Z


# direct methods
.method public static constructor <clinit>()V
    .locals 3

    const/4 v0, 0x7

    new-array v2, v0, [Ljava/lang/String;

    const/4 v1, 0x0

    const-string v0, "omx.sprd.av1.decoder"

    aput-object v0, v2, v1

    const/4 v1, 0x1

    const-string v0, "c2.qti.av1.decoder"

    aput-object v0, v2, v1

    const/4 v1, 0x2

    const-string v0, "c2.qti.av1.decoder.low_latency"

    aput-object v0, v2, v1

    const/4 v1, 0x3

    const-string v0, "c2.exynos.av1.decoder"

    aput-object v0, v2, v1

    const/4 v1, 0x4

    const-string v0, "c2.mtk.av1.decoder"

    aput-object v0, v2, v1

    const/4 v1, 0x5

    const-string v0, "omx.mtk.video.decoder.av1"

    aput-object v0, v2, v1

    const/4 v1, 0x6

    const-string v0, "c2.unisoc.av1.decoder"

    invoke-static {v0, v2, v1}, LX/DiN;->A0v(Ljava/lang/Object;[Ljava/lang/Object;I)Ljava/util/HashSet;

    move-result-object v0

    sput-object v0, LX/FU8;->A0m:Ljava/util/HashSet;

    return-void
.end method

.method public constructor <init>()V
    .locals 8

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v1, 0x0

    const/4 v2, 0x1

    const/4 v5, -0x1

    new-instance v0, LX/GRP;

    invoke-direct {v0}, LX/GRP;-><init>()V

    iput-object v0, p0, LX/FU8;->A0F:LX/GRP;

    sget-object v0, Lcom/facebook/video/heroplayer/setting/HeroPlayerSetting;->A00:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-object v0, p0, LX/FU8;->A0G:Lcom/facebook/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-boolean v1, p0, LX/FU8;->A0Z:Z

    const/4 v0, 0x3

    iput v0, p0, LX/FU8;->A02:I

    const/16 v3, 0x7d0

    const-string v0, "ExoService"

    iput-object v0, p0, LX/FU8;->A0N:Ljava/lang/String;

    iput-boolean v2, p0, LX/FU8;->A0k:Z

    new-instance v0, LX/EzJ;

    invoke-direct {v0}, Ljava/lang/Object;-><init>()V

    iget-boolean v2, v0, LX/EzJ;->A00:Z

    new-instance v0, LX/GRX;

    invoke-direct {v0, v2}, LX/GRX;-><init>(Z)V

    iput-object v0, p0, LX/FU8;->A0E:LX/GRX;

    const/16 v6, 0x1f4

    new-instance v0, LX/GRZ;

    invoke-direct {v0, v6, v3}, LX/GRZ;-><init>(II)V

    iput-object v0, p0, LX/FU8;->A0K:LX/GRZ;

    new-instance v0, LX/GRZ;

    invoke-direct {v0, v1, v1}, LX/GRZ;-><init>(II)V

    iput-object v0, p0, LX/FU8;->A0L:LX/GRZ;

    const/16 v4, 0xfa0

    new-instance v0, LX/GRW;

    invoke-direct {v0}, LX/GRW;-><init>()V

    iput-object v0, p0, LX/FU8;->A0I:LX/GRW;

    new-instance v0, LX/K6w;

    invoke-direct {v0}, LX/K6w;-><init>()V

    iput-object v0, p0, LX/FU8;->A0C:LX/K6w;

    sget-object v0, LX/GRf;->A00:LX/GRf;

    iput-object v0, p0, LX/FU8;->A0B:LX/GRf;

    new-instance v0, LX/GR9;

    invoke-direct {v0}, LX/GR9;-><init>()V

    iput-object v0, p0, LX/FU8;->A0A:LX/GR9;

    new-instance v2, LX/Ez5;

    invoke-direct {v2}, LX/Ez5;-><init>()V

    new-instance v0, LX/GRO;

    invoke-direct {v0, v2}, LX/GRO;-><init>(LX/Ez5;)V

    iput-object v0, p0, LX/FU8;->A09:LX/GRO;

    new-instance v0, LX/GRB;

    invoke-direct {v0}, LX/GRB;-><init>()V

    iput-object v0, p0, LX/FU8;->A0D:LX/GRB;

    new-instance v0, LX/GRE;

    invoke-direct {v0}, LX/GRE;-><init>()V

    iput-object v0, p0, LX/FU8;->A0M:LX/GRE;

    new-instance v2, LX/F7T;

    invoke-direct {v2}, Ljava/lang/Object;-><init>()V

    const v0, 0x186a0

    iput v0, v2, LX/F7T;->A00:I

    const/16 v0, 0x3e8

    iput v0, v2, LX/F7T;->A03:I

    iput v6, v2, LX/F7T;->A02:I

    const/16 v0, 0xfa

    iput v0, v2, LX/F7T;->A01:I

    new-instance v0, LX/GRI;

    invoke-direct {v0, v2}, LX/GRI;-><init>(LX/F7T;)V

    iput-object v0, p0, LX/FU8;->A06:LX/GRI;

    new-instance v2, LX/F7T;

    invoke-direct {v2}, Ljava/lang/Object;-><init>()V

    iput v3, v2, LX/F7T;->A00:I

    const v0, 0x249f0

    iput v0, v2, LX/F7T;->A03:I

    const v0, 0x86470

    iput v0, v2, LX/F7T;->A02:I

    const v0, 0x1e8480

    iput v0, v2, LX/F7T;->A01:I

    new-instance v0, LX/GRI;

    invoke-direct {v0, v2}, LX/GRI;-><init>(LX/F7T;)V

    iput-object v0, p0, LX/FU8;->A07:LX/GRI;

    iput-boolean v1, p0, LX/FU8;->A0d:Z

    iput-boolean v1, p0, LX/FU8;->A0h:Z

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FU8;->A0O:Ljava/util/HashSet;

    const-wide/16 v2, 0x0

    iput-wide v2, p0, LX/FU8;->A05:J

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FU8;->A0Q:Ljava/util/Set;

    invoke-static {}, LX/1ac;->A1A()Ljava/util/HashMap;

    move-result-object v0

    iput-object v0, p0, LX/FU8;->A0P:Ljava/util/Map;

    iput-boolean v1, p0, LX/FU8;->A0e:Z

    const/16 v0, 0x7530

    iput v0, p0, LX/FU8;->A01:I

    iput v5, p0, LX/FU8;->A04:I

    iput v4, p0, LX/FU8;->A00:I

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FU8;->A0V:Ljava/util/Set;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FU8;->A0U:Ljava/util/Set;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FU8;->A0W:Ljava/util/Set;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FU8;->A0R:Ljava/util/Set;

    new-instance v0, LX/GRM;

    invoke-direct {v0}, LX/GRM;-><init>()V

    iput-object v0, p0, LX/FU8;->A0J:LX/GRM;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FU8;->A0T:Ljava/util/Set;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FU8;->A0S:Ljava/util/Set;

    invoke-static {}, LX/1ac;->A1B()Ljava/util/HashSet;

    move-result-object v0

    iput-object v0, p0, LX/FU8;->A0X:Ljava/util/Set;

    const/4 v0, 0x0

    iput-object v0, p0, LX/FU8;->A0H:LX/GRQ;

    iput-boolean v1, p0, LX/FU8;->A0g:Z

    iput-boolean v1, p0, LX/FU8;->A0c:Z

    iput-boolean v1, p0, LX/FU8;->A0b:Z

    iput-boolean v1, p0, LX/FU8;->A0a:Z

    const/16 v3, 0x3e8

    const/16 v4, 0x7d0

    const v7, 0x8000

    new-instance v2, LX/Dwr;

    move v6, v3

    move v5, v3

    invoke-direct/range {v2 .. v7}, LX/Dwr;-><init>(IIIII)V

    iput-object v2, p0, LX/FU8;->A08:LX/Dwr;

    const/16 v0, 0x1a

    iput v0, p0, LX/FU8;->A03:I

    iput-boolean v1, p0, LX/FU8;->A0l:Z

    iput-boolean v1, p0, LX/FU8;->A0Y:Z

    iput-boolean v1, p0, LX/FU8;->A0j:Z

    iput-boolean v1, p0, LX/FU8;->A0f:Z

    return-void
.end method
