.class public LX/GRl;
.super Ljava/lang/Object;
.source ""

# interfaces
.implements Ljava/io/Serializable;


# static fields
.field public static final A00:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

.field public static final A01:LX/GRl;

.field public static final serialVersionUID:J = -0xb6b8c66d093f82bL


# instance fields
.field public final abrMonitorEnabled:Z

.field public final abrSetting:LX/K6x;

.field public final adBreakEnahncedPrefetchDurationMs:I

.field public final adjustSpeedBottomThresholdMs:I

.field public final adjustSpeedTopThresholdMs:I

.field public final advanceSegmentOnNetworkErrors:J

.field public final aggressiveEdgeLatencyForLsbConfPercentile:I

.field public final aggressiveEdgeLatencyOverrideForLSB:J

.field public final allowImmediateLiveBufferTrim:Z

.field public final allowMultiPlayerFormatWarmup:Z

.field public final allowOutOfBoundsAccessForPDash:Z

.field public final allowOverridingPlayerWarmUpWatermark:Z

.field public final allowPredictiveAlignment:Z

.field public final allowRequestForSoftwareDecoder:Z

.field public final allowedExtendedMinRebuffePeriodMs:I

.field public final allowedExtendedPremiumTierRebufferPeriodMs:I

.field public final allowedExtendedRebufferPeriodMs:I

.field public final alwaysPerformContentLengthUpdateFirst:Z

.field public final alwaysPrefetchInBgDefaultPriorityThread:Z

.field public final alwaysPrefetchInIdleExecutor:Z

.field public final alwaysReuseManifestFetcher:Z

.field public final appendReconfigurationDataForDrmContentFix:Z

.field public final asyncReleaseSurfaceOnMainThread:Z

.field public final attachGrootPlayerListenerWhenUsingSurfaceControl:Z

.field public final audioBufferSize:I

.field public final audioLazyLoadSetting:LX/GRC;

.field public final audioStallCountThresholdMs:I

.field public final audioTrackInitFailedFallbackApplyThreshold:I

.field public final audioVideoSyncPeriodMs:I

.field public final autogenSettings:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

.field public final av1Dav1dEnableVpsLogging:Z

.field public final av1Dav1dUseSurfaceViewSetFix:Z

.field public final av1FlushDav1dProperly:Z

.field public final av1SetBuffersDataspace:Z

.field public final av1ThrowExceptionOnNonDav1dDecoder:Z

.field public final av1ThrowExceptionOnPictureError:Z

.field public final av1UseDav1dSynchronizationFixes:Z

.field public final av1UseMemoryCleanupFixes:Z

.field public final avoidSecondPhaseOnCell:Z

.field public final avoidServiceClassLoadOnClient:Z

.field public final bandwidthMultiplierForAggressiveEdgeLatency:F

.field public final bandwidthMultiplierToSkipPrefetchedContent:F

.field public final bgHeroServiceStatusUpdate:Z

.field public final blackscreenDetectOnce:Z

.field public final blackscreenNoSampleThresholdMs:J

.field public final blackscreenSampleIntervalMs:J

.field public final blockDRMPlaybackOnHDMI:Z

.field public final blockDRMScreenCapture:Z

.field public final blockListedHardwareDecoderMap:Ljava/util/HashMap;

.field public final broadcasterIdAllowlist:Ljava/lang/String;

.field public final bufferDecreaseTimeMs:I

.field public final bufferedCacheDataSinkSize:I

.field public final bufferedDurationBasedHttpPriorityLowerBoundMs:I

.field public final bufferedDurationBasedHttpPriorityUpperBoundMs:I

.field public final bypassGreaterThanMinRebufferWhenBeforePlay:Z

.field public final cache:LX/GRK;

.field public final callbackFirstCaughtStreamError:Z

.field public final cancelOngoingRequest:Z

.field public final cellMaxWatermarkMsConfig:LX/GRG;

.field public final changePriorityForPrefetchRequestOnPlayerStart:Z

.field public final changeThreadPriorityForPrefetch:Z

.field public final checkCachedLockedCacheSpan:Z

.field public final checkLiveSourceUri:Z

.field public final checkManifestRepresentationFormatMismatch:Z

.field public final checkPlayerStateIntervalIncreaseMs:I

.field public final checkPlayerStateMaxIntervalMs:I

.field public final checkPlayerStateMinIntervalMs:I

.field public final checkReadToEndBeforeUpdatingFinalState:Z

.field public final checkThumbnailCache:Z

.field public final chunkSourceRetryMaximum:I

.field public final cleanUpHeartbeatMessagesIfNotPlaying:Z

.field public final cleanUpHeartbeatMessagesOnPause:Z

.field public final cleanUpHeartbeatMessagesOnStall:Z

.field public final clearBufferingWhenInWarmup:Z

.field public final combineInitFirstSegment:Z

.field public final concatenatedMsPerLoadConfig:LX/GRG;

.field public final continueLoadingOnSeekbarExo2:Z

.field public final continuouslyLoadFromPreSeekLocation:Z

.field public final customizedPrefetchThreadPriority:I

.field public final customizedWABufferForPlaybackMs:I

.field public final customizedWAIndividualAllocationSize:I

.field public final customizedWARebufferMs:I

.field public final dashHighWatermarkMs:I

.field public final dashLowWatermarkMs:I

.field public final dashManifestPoolSize:I

.field public final dav1dApplyGrain:Z

.field public final dav1dMaxFrameDelay:I

.field public final dav1dThreads:I

.field public final decoderDequeueRetryTimeMs:I

.field public final decoderInitializationRetryTimeMs:I

.field public final defaultUserAgent:Ljava/lang/String;

.field public final delayWarmupRunningMs:I

.field public final depthTocheckSurfaceInvisibleParent:I

.field public final desiredBufferAcceptableErrorMs:I

.field public final disableAudioFocusInGroot:Z

.field public final disableAudioRendererOnAudioTrackInitFailed:Z

.field public final disableCapBufferSizeLocalProgressive:Z

.field public final disableIsCachedApi:Z

.field public final disableLatencyManagerOnStaticManifest:Z

.field public final disableLiveCaptioningOnPlayerInit:Z

.field public final disableLoadingRetryOnFatalError:Z

.field public final disableNetworkErrorCountInChunkSource:Z

.field public final disablePoolingForDav1dMediaCodec:Z

.field public final disablePreallocateCodecDuringStartup:Z

.field public final disableRecoverInBackground:Z

.field public final disableSecondPhasePrefetchForDataSaver:Z

.field public final disableSecondPhasePrefetchForReels:Z

.field public final disableSecondPhasePrefetchOnAppScrolling:Z

.field public final disableSkipInlineForHuddle:Z

.field public final disableSpeedAdjustmentOnBadUserExperience:Z

.field public final disableStoriesCustomizedUnstallBuffer:Z

.field public final disableTextEraLoggingOnLoadRetry:Z

.field public final disableTextRendererOn404InitSegmentLoadError:Z

.field public final disableTextRendererOn404LoadError:Z

.field public final disableTextRendererOn500InitSegmentLoadError:Z

.field public final disableTextRendererOn500LoadError:Z

.field public final disableTextTrackOnMissingTextTrack:Z

.field public final disableTigonBandwidthLogging:Z

.field public final disableUllBasedOnHoldout:Z

.field public final disableVideoTrackForInVisibleVDD:Z

.field public final dontRetry403OnExpiredUrl:Z

.field public final drmSessionStoreCapacity:I

.field public final dummyDefaultSetting:Z

.field public final dynamicDiscontinuityInitialPosMs:I

.field public final dynamicInfoSetting:LX/GRL;

.field public final earlyPreallocateCodecOnAppNotScrolling:Z

.field public final earlyPreallocateCodecOnIdle:Z

.field public final enable204SegmentRemapping:Z

.field public final enable404SegmentRemapping:Z

.field public final enable416Logging:Z

.field public final enable500R1FallbackLogging:Z

.field public final enableAV1SRShader:Z

.field public final enableActiveDrmSessionStoreRelease:Z

.field public final enableAdBreakEnhancedPrefetch:Z

.field public final enableAdditionalDecoderInitFailureMessage:Z

.field public final enableAllLongerPrefetchAds:Z

.field public final enableAlwaysCallPreallocateCodec:Z

.field public final enableAsynchronousBufferQueueing:Z

.field public final enableAudioTrackRetry:Z

.field public final enableAv1Dav1d:Z

.field public final enableAv1LibGav1:Z

.field public final enableAvc1ColorConfigParseFix:Z

.field public final enableBackgroundServicePlayerReuse:Z

.field public final enableBackwardJumpSeekKeyframeSync:Z

.field public final enableBitrateAwareAudioPrefetch:Z

.field public final enableBlackscreenDetector:Z

.field public final enableBlockListingResource:Z

.field public final enableBoostOngoingPrefetchPriorityPlay:Z

.field public final enableBoostOngoingPrefetchPriorityPrepare:Z

.field public final enableBufferAwareJumpSeek:Z

.field public enableBusySignalToFramework:Z

.field public final enableCDNDebugHeaders:Z

.field public final enableCacheBlockWithoutTimeout:Z

.field public final enableCacheLookUp:Z

.field public final enableCacheNetworkTypeIfNotSet:Z

.field public final enableCachedBandwidthEstimate:Z

.field public final enableCancelFollowupPrefetch:Z

.field public final enableCancelOngoingPrefetchPause:Z

.field public final enableCancelOngoingRequestPause:Z

.field public final enableCancelPrefetchInQueuePrepare:Z

.field public final enableCaseInsensitiveHttpResponseHeaderKey:Z

.field public final enableCheckAudioError:Z

.field public final enableClearStallOnBroadcastEnd:Z

.field public final enableClockSync:Z

.field public final enableCodecDeadlockFix:Z

.field public final enableCodecHistoryOverlayField:Z

.field public final enableCodecPreallocation:Z

.field public final enableContinueLoadingLoggingForManifest:Z

.field public final enableContinueLoadingLoggingForMedia:Z

.field public final enableCreateByteBufferFromABufferNullCheckHooks:Z

.field public final enableCustomizedDRCEffect:Z

.field public final enableCustomizedDRCForHeadset:Z

.field public final enableCustomizedPrefetchThreadPriority:Z

.field public final enableCustomizedXHEAACConfig:Z

.field public final enableDashManifestPool:Z

.field public final enableDav1dAsMediaCodecAdapter:Z

.field public final enableDav1dOpenGLIncorrectSurfaceSizeFix:Z

.field public final enableDav1dOpenGLRendering:Z

.field public final enableDav1dOpenGLRenderingHandleAspectRatio:Z

.field public final enableDebugLogs:Z

.field public final enableDeduplicateImfEmsgAtPlayer:Z

.field public final enableDelayWarmupRunning:Z

.field public final enableDemoteOngoingPrefetchPriorityPause:Z

.field public final enableDrmProvisioningRetry:Z

.field public final enableDrmSessionStore:Z

.field public final enableDynamicCursorDistance:Z

.field public final enableDynamicDiscontinuityDistance:Z

.field public final enableDynamicMinRebufferMsController:Z

.field public enableDynamicPrefetchCacheFileSize:Z

.field public enableDynamicPrefetchCacheFileSizePrefetchOnly:Z

.field public final enableE2ECDNTracing:Z

.field public final enableEmsgPtsAlignment:Z

.field public final enableEmsgTrackForAll:Z

.field public final enableEnsureBindService:Z

.field public final enableEvictCacheOnExoplayerErrors:Z

.field public final enableEvictPlayerOnAudioTrackInitFailed:Z

.field public final enableExcessiveNumUriRedirectLogging:Z

.field public final enableExplicitTextDataSourceCreation:Z

.field public final enableFBLiteHttpDataSource:Z

.field public final enableFallbackToMainProcess:Z

.field public final enableFillBufferHooks:Z

.field public final enableFillFreeBufferCheckNodeHooks:Z

.field public final enableFirstWarmUpRequestOnScreen:Z

.field public final enableFixForOnPreparingCallback:Z

.field public final enableFixRemovePlayerViewFromParent:Z

.field public final enableFixTrackIndexOOB:Z

.field public final enableFrameBasedLogging:Z

.field public final enableFreeNodeHooks:Z

.field public final enableGlobalNetworkMonitor:Z

.field public final enableGlobalStallMonitor:Z

.field public final enableGrootAlwaysSendPlayStarted:Z

.field public final enableHeroPlayerMaxLoopCount:Z

.field public final enableHttpPriorityForPrefetch:Z

.field public final enableHttpPriorityForStreaming:Z

.field public final enableHybridCacheForPrefetch:Z

.field public final enableIgHttpDataSource:Z

.field public final enableInstreamAdsEmsgLog:Z

.field public final enableIsTextAdaptationSetNotFoundLogging:Z

.field public final enableJumpTrackFallingBehind:Z

.field public final enableKillProcessBeforeRebind:Z

.field public final enableKillVideoProcessForAudioTrackInitFailed:Z

.field public final enableKillVideoProcessForIllegalStateException:Z

.field public final enableLastPlaybackSpeedCacheUpdate:Z

.field public final enableLatencyManagerRateLimiting:Z

.field public final enableLatencyPlaybackSpeed:Z

.field public final enableLazyAudioLoadForProgressive:Z

.field public final enableLiveBWEstimation:Z

.field public final enableLiveBroadcastErrorUI:Z

.field public final enableLiveBufferMeter:Z

.field public final enableLiveJumpByTrimBuffer:Z

.field public final enableLiveLatencyManager:Z

.field public final enableLiveOneTimeLoadingJump:Z

.field public final enableLiveTierSpecificBufferSetting:Z

.field public final enableLiveTierSpecificRebuffer:Z

.field public final enableLoadErrorHandlingPolicy:Z

.field public final enableLoaderRetryLoggingForManifest:Z

.field public final enableLoaderRetryLoggingForMedia:Z

.field public final enableLogExceptionMessageOnError:Z

.field public final enableLogSemiCachedEvents:Z

.field public final enableLoggingEmptyOrNullVideoId:Z

.field public final enableLongCacheKeyForContentLength:Z

.field public final enableLowLatencyDecoding:Z

.field public final enableLowLatencyDecodingOverrideSDKGating:Z

.field public final enableMP3Extractor:Z

.field public final enableMediaCodecPoolingForLiveAudio:Z

.field public final enableMediaCodecPoolingForLiveVideo:Z

.field public final enableMediaCodecPoolingForProgressiveAudio:Z

.field public final enableMediaCodecPoolingForProgressiveVideo:Z

.field public final enableMediaCodecPoolingForVodAudio:Z

.field public final enableMediaCodecPoolingForVodVideo:Z

.field public final enableMediaCodecReuseOptimizeLock:Z

.field public final enableMediaCodecReuseOptimizeRelease:Z

.field public final enableMediaSessionControls:Z

.field public final enableMemoryAwareBufferSizeUsingRed:Z

.field public final enableMemoryAwareBufferSizeUsingYellow:Z

.field public final enableMixeCodecManifestLogging:Z

.field public final enableMixeCodecManifestVideoCodecSwitchedLogging:Z

.field public final enableMixedCodecManifestSupport:Z

.field public final enableMp3Mp4ExtractorLogic:Z

.field public final enableMp4MultiTrafBoxesFix:Z

.field public final enableMpdFilteringUtils:Z

.field public final enableNeedCenteringIndependentlyGroot:Z

.field public final enableOffloadInitHeroService:Z

.field public final enableOffloadingIPC:Z

.field public final enableOnMessageReceivedHooks:Z

.field public final enableOnOMXEmptyBufferDoneHooks:Z

.field public final enableOneSemanticsLoaderRetry:Z

.field public final enableOpenGLSurfaceSizeUpdateFix:Z

.field public final enableOverrideBufferWatermark:Z

.field public final enableOverrideEndPosition:Z

.field public final enablePCMBufferListener:Z

.field public final enablePIDForHuddle:Z

.field public final enablePauseNow:Z

.field public final enablePlayerActionStateLoggingInFlytrap:Z

.field public final enablePreSeekToApi:Z

.field public final enablePredictedUrlTracing:Z

.field public final enablePrefetchCancelCallback:Z

.field public final enableProgressiveFallbackWhenNoRepresentations:Z

.field public final enableProgressivePrefetchWhenNoRepresentations:Z

.field public final enableQuickDashPlayback:Z

.field public final enableRebootDeviceErrorUIForAudioTrackInitFailed:Z

.field public final enableRebootDeviceErrorUIForCodecInitFailed:Z

.field public final enableRebootDeviceErrorUIForIllegalStateException:Z

.field public final enableReduceRetryBeforePlay:Z

.field public final enableRequestAnalyticsTagsHeaderLogging:Z

.field public final enableRequestEtdHeader:Z

.field public final enableRetryErrorLoggingInCancel:Z

.field public final enableRetryOnConnection:Z

.field public final enableRetryWarmup:Z

.field public final enableSaturation:Z

.field public final enableSeamlessAudioCodecAdaptation:Z

.field public final enableSecondPhaseAlignment:Z

.field public final enableSecondPhasePrefetch:Z

.field public final enableSecondPhasePrefetchWebm:Z

.field public final enableSecondaryChannelLoggingForLite:Z

.field public final enableSegmentIndexCheckForPrefetchBytes:Z

.field public final enableSendCommandHooks:Z

.field public final enableServerSideAbr:Z

.field public final enableServerSideForwardBwe:Z

.field public final enableServerSideForwardTracing:Z

.field public final enableSpatialOpusRendererExo2:Z

.field public final enableSsBweHeaderForLive:Z

.field public final enableStopWarmupSchedulerEmpty:Z

.field public final enableStreamLatencyToggleOverride:Z

.field public final enableSuspensionAfterBroadcasterStall:Z

.field public final enableSynchronizeCodecInteractionsWithQueueing:Z

.field public final enableSystrace:Z

.field public final enableTextTrackWithKnownLanguage:Z

.field public final enableTransferListenerCallbackPerfFix:Z

.field public final enableUnexpectedExoExceptionLogging:Z

.field public final enableUnifiedGrootErrorHandling:Z

.field public final enableUpdateProgressiveContentLengthFromCache:Z

.field public final enableUsingASRCaptions:Z

.field public final enableVideoDebugEventLogging:Z

.field public final enableVideoHybridCache:Z

.field public final enableVideoMemoryCache:Z

.field public final enableVideoPlayerServerSideBweAnnotations:Z

.field public final enableVideoPositionLoggingInCompleteEvent:Z

.field public final enableVodContentLengthLogging:Z

.field public final enableVodDrmPrefetch:Z

.field public final enableVodPausedLoading:Z

.field public final enableVp9CodecPreallocation:Z

.field public final enableVrlQplLoggingEvents:Z

.field public final enableWarmCodec:Z

.field public final enableWarmUpRequestOffscreen:Z

.field public final enableWarmupProcessPeriodically:Z

.field public final enableWarmupScheduler:Z

.field public final enableWarmupSchedulerRightAway:Z

.field public final enableWarmupSkipScheduler:Z

.field public final enableWifiLockManager:Z

.field public final enableWifiLongerPrefetchAds:Z

.field public final enabledViewManagementInGroot:Z

.field public final enforceSizeLimitOnSecondPhasePrefetch:Z

.field public final enhanceParseException:Z

.field public final errorRecoveryAttemptRepeatCountFlushThreshold:I

.field public final exceedRendererCapabilitiesIfAllFilteredOut:Z

.field public final excessiveUriRedirectLoggingLimit:I

.field public final exo2ReuseManifestAfterInitialParse:Z

.field public final exo2Vp9UseSurfaceRenderer:Z

.field public final exoPlayerUpgrade218verifyApplicationThread:Z

.field public final expBackOffSpeedUp:F

.field public final expBackoffInRetryBaseDelay:I

.field public final extendedApiTierLiveRebufferThresholdMs:I

.field public final extendedLiveRebufferThresholdMs:I

.field public final extendedMinRebufferThresholdMs:I

.field public final extendedPremiumTierLiveRebufferThresholdMs:I

.field public final fallbackToFirstSegment:Z

.field public final fbstoriesMinBufferMsConfig:LX/GRG;

.field public final fbstoriesMinRebufferMsConfig:LX/GRG;

.field public final fetchCacheSourceHttpConnectTimeoutMsConfig:LX/GRG;

.field public final fetchHttpReadTimeoutMsConfig:LX/GRG;

.field public final fixBlackscreenByRecreatingSurface:Z

.field public final fixDRMPlaybackOnHDMI:Z

.field public final fixNullCacheSpan:Z

.field public final fixPeriodTransitionWithNonZeroStartPosition:Z

.field public final fixSurfaceInvisibleParent:Z

.field public final fixXmlParserError:Z

.field public final forceAdjustSurfaceOnMainThread:Z

.field public final forceDisableULL:Z

.field public final forceMainThreadHandlerForHeroSurface:Z

.field public final forceManifestFilteringMode:I

.field public final forceMinWatermarkGreaterThanMinRebuffer:Z

.field public final forceOneSemanticsHandling:Z

.field public final forceOneSemanticsWaveHandling:I

.field public final forceSeekRushPlayback:Z

.field public final forceStereoToMonoConversion:Z

.field public final fragmentedMp4ExtractorVersion:I

.field public final frequentApiTierBroadcasterStallIntervalThresholdMs:I

.field public final frequentBroadcasterStallIntervalThresholdMs:I

.field public final frequentPremiumTierBroadcasterStallIntervalThresholdMs:I

.field public final frequentStallIntervalThresholdMs:I

.field public final fullscreenPredictionRequestTimeoutMs:J

.field public final getMinLoadPositionStartOfPlayback:Z

.field public final getPlaybackPrefFromPrefetchRequest:Z

.field public final globalStallCountsToUpdateDynamicRebuffer:I

.field public final globalStallCountsToUpdateLiveDynamicRebuffer:I

.field public final goodVsrScoreThreshold:I

.field public final handleReleasedReusedSurfaceTexture:Z

.field public final handlerThreadPoolSize:I

.field public final highJumpDistanceMs:I

.field public final huddleLatencyMaxSpeedDelta:F

.field public final ignore404AfterStreamEnd:Z

.field public final ignoreEmptyProfileLevels:Z

.field public final ignoreLiveStreamErrorsTimeoutMs:J

.field public final ignoreStreamErrorsTimeoutMs:J

.field public final ignoreTemplatedMinLoadPosition:Z

.field public final improveLooping:Z

.field public final includeAllBufferingEvents:Z

.field public final includeLiveTraceHeader:Z

.field public final includePlaybackSessionIdHeader:Z

.field public final initChunkCacheSize:I

.field public final initialBufferTrimPeriodMs:I

.field public final initialBufferTrimTargetMs:I

.field public final initialBufferTrimThresholdMs:I

.field public final intentBasedBufferingConfig:LX/GRV;

.field public final isAbrTracingEnabled:Z

.field public final isAudioDataSummaryEnabled:Z

.field public final isDefaultMC:Z

.field public final isEarlyPreallocateCodec:Z

.field public final isExo2AggresiveMicrostallFixEnabled:Z

.field public final isExo2DrmEnabled:Z

.field public final isExo2MediaCodecReuseEnabled:Z

.field public final isExo2UseAbsolutePosition:Z

.field public final isExo2Vp9Enabled:Z

.field public final isLiveTraceEnabled:Z

.field public final isMeDevice:Z

.field public final isSetSerializableBlacklisted:Z

.field public final isTATracingEnabled:Z

.field public final isVideoQplPipelineEnabled:Z

.field public final jumpSeekPosLeftoverBufferDurationMs:I

.field public final jumpSeekReductionFactorPct:I

.field public final killVideoProcessOnExoPlaybackExceptionMaximumRetryCount:I

.field public final killVideoProcessOnExoPlaybackExceptionRetryTimeMs:J

.field public final killVideoProcessWhenMainProcessDead:Z

.field public final largeBandwidthCursorMs:I

.field public final largeBandwidthToleranceMs:I

.field public final largeJumpBandwidthMultiplier:F

.field public final lateNightHourLowerThreshold:I

.field public final lateNightHourUpperThreshold:I

.field public final latencyBoundMsConfig:LX/GRG;

.field public final latencyControllerBypassLimits:Z

.field public final liveAPIMinBufferMsConfig:LX/GRG;

.field public final liveAPIMinRebufferMsConfig:LX/GRG;

.field public final liveBufferDurationFluctuationTolerancePercent:I

.field public final liveBufferMeterTrimByMinBuffer:Z

.field public final liveDashEdgeLatencyMs:I

.field public final liveDashHighWatermarkMs:I

.field public final liveDashLowWatermarkMs:I

.field public final liveEnableStreamingCache:Z

.field public final liveLatencyManagerPlayerFormat:Ljava/lang/String;

.field public final liveLatencySettings:Ljava/util/Map;

.field public final liveMinBufferMsConfig:LX/GRG;

.field public final liveMinRebufferMsConfig:LX/GRG;

.field public final liveMinRetryCounts:I

.field public final livePremiumMinBufferMsConfig:LX/GRG;

.field public final livePremiumMinRebufferMsConfig:LX/GRG;

.field public final livePrioritizeTimeOverSizeThresholds:Z

.field public final liveTrimByBufferMeterMinDeltaMs:I

.field public final liveUseLowPriRequests:Z

.field public final logLatencyEvents:Z

.field public final logOnApacheFallback:Z

.field public final logPausedSeekPositionBeforeSettingState:Z

.field public final logStallOnPauseOnError:Z

.field public final loggerSDKConfig:LX/GRH;

.field public final lowJumpDistanceMs:I

.field public final mEventLogSetting:LX/GR2;

.field public final mLowLatencySetting:LX/GR3;

.field public final manifestErrorReportingExo2:Z

.field public final manifestMisalignmentReportingExo2:Z

.field public maxAllowed503RetryCount:I

.field public final maxBufferDurationPausedLiveUs:J

.field public final maxBufferToDownloadInPausedLoadingMs:I

.field public final maxBytesToPrefetchCellVOD:I

.field public final maxBytesToPrefetchVOD:I

.field public final maxCustomizedWABufferMs:I

.field public final maxDistanceBetweenTracksMs:I

.field public final maxDurationUsForFullSegmentPrefetch:J

.field public final maxMediaCodecInstancesPerCodecName:I

.field public final maxMediaCodecInstancesTotal:I

.field public final maxNumGapsToNotify:I

.field public final maxNumRedirects:I

.field public final maxPastOtherTrackDistanceMs:I

.field public final maxPredictedSegmentsToRemap:I

.field public final maxRetryCountByEvictCacheOnExoplayerErrors:I

.field public final maxRetryCountByEvictPlayerOnAudioTrackInitFailed:I

.field public final maxSegmentsToAdvance:J

.field public final maxSegmentsToPredict:I

.field public final maxStaleManifestCountForDiscontinuityJumps:I

.field public final maxTimeAllowedSpentInPausedLoadingMs:I

.field public final maxTimeMsSinceRefreshPDash:I

.field public final maxTimeToSkipInlineManifestMs:I

.field public final maxTrackJumpsAllowed:I

.field public final maxWidthForAV1SRShader:I

.field public final maxWifiBytesToPrefetchAds:I

.field public final maxWifiPrefetchDurationMsAds:I

.field public final maybeSkipInlineManifestForLSB:Z

.field public final mcDebugState:Ljava/lang/String;

.field public final mcValueSource:Ljava/lang/String;

.field public final microStallThresholdMsToUseMinBuffer:I

.field public final minBufferForPreSeekMs:J

.field public final minBufferMsConfig:LX/GRG;

.field public final minBufferedDurationMsToCancel:I

.field public minCacheFileSizeForDynamicChunkingInBytes:J

.field public final minCustomizedWABufferMs:I

.field public final minDelayToRefreshTigonBitrateMs:J

.field public final minLiveStartPositionMs:I

.field public final minMicroRebufferMsConfig:LX/GRG;

.field public final minNumManifestForOutOfBoundsPDash:I

.field public final minRebufferMsConfig:LX/GRG;

.field public final minRetryCountBeforePlay:I

.field public final minScoreThresholdForLL:I

.field public final minTimeBetweenDynamicCursorChangesMs:I

.field public final minTimeBetweenStallToIgnoreDiscontJumpS:I

.field public final minTimeToSkipInlineManifestMs:I

.field public final minimumLogLevel:I

.field public final minimumTimeBetweenSpeedChangesS:I

.field public final minimumTimeBetweenStallsS:I

.field public final needUpdatePlayerStateThresholdMs:I

.field public final needUpdateStateByPositionOffsetThresholdMs:I

.field public final networkAwareDisableSecondPhasePrefetch:LX/GRG;

.field public final networkAwareHttpPriorityIncrementalForStreaming:LX/GRG;

.field public final networkAwarePrefetchTaskQueueWorkerNum:LX/GRG;

.field public final newDownstreamFormatChange:Z

.field public final numDashChunkMemoryCacheSampleStreams:I

.field public final numMsToPrefetch:I

.field public final numOfBytesBeforeLoaderThreadSleep:I

.field public final numSegmentsToSecondPhasePrefetch:I

.field public final numSegmentsToSecondPhasePrefetchAudio:I

.field public final numSegmentsToSecondPhasePrefetchXHEAACAudio:I

.field public final offloadGrootAudioFocus:Z

.field public final oneSemanticsOsParamValue:Ljava/lang/String;

.field public final originAllowlistForAlternateCodec:Ljava/util/Set;

.field public final parseAndAttachETagManifest:Z

.field public final parseManifestIdentifier:Z

.field public final pausePlayingVideoWhenRelease:Z

.field public final pausedLoadingTriggerTypes:Ljava/util/Set;

.field public final pidMultiplierFloor:F

.field public final pidParameterExpBackOff:F

.field public final pidParameterMultiplierInitial:F

.field public final playbackAboutToFinishCallbackTriggeringRemainingDuration:I

.field public final playerOriginPausedLoadingBlackList:Ljava/lang/String;

.field public final playerPoolSize:I

.field public final playerRespawnExo2:Z

.field public final playerWarmUpPoolSize:I

.field public final playerWarmUpWatermarkMs:I

.field public final playerWatermarkBeforePlayedMs:I

.field public final postStoriesGrootPrefetchToHeroManagerThread:Z

.field public final predictedHuddleDashManifestReadTimeoutMs:I

.field public final predictedLiveDashManifestReadTimeoutMs:I

.field public final predictionMaxSegmentDurationMs:I

.field public final predictiveDashReadTimeoutMs:I

.field public final predictiveDashSetting:LX/GRj;

.field public final prefetchAudioFirst:Z

.field public final prefetchAudioFirstForStoriesAds:Z

.field public final prefetchBypassFilter:Z

.field public final prefetchSubOriginBlockList:Ljava/lang/String;

.field public final prefetchTagBlockList:Ljava/lang/String;

.field public final prefetchTaskQueuePutInFront:Z

.field public final prefetchTaskQueueRetryNumber:I

.field public final prefetchTaskQueueSize:I

.field public final prefetchTaskQueueWorkerNum:I

.field public final prefetchThreadUpdatedPriority:I

.field public final prefetchUrgentTaskQueueWorkerNum:I

.field public final preventAdjustWhenSurfaceNotValid:Z

.field public final preventJumpStaticManifest:Z

.field public final preventPreallocateIfNotEmpty:Z

.field public final preventTextRendererDelay:Z

.field public final preventWarmupInvalidSource:Z

.field public final prioritizeAv1Dav1dOverLibgav1:Z

.field public final prioritizeAv1HardwareDecoder:Z

.field public final prioritizeTimeOverSizeThresholds:Z

.field public final progressivePrefetchBytesCell:I

.field public final progressivePrefetchBytesWifi:I

.field public final proxyDrmProvisioningRequests:Z

.field public final qualityMapperBoundMsConfig:LX/GRG;

.field public final quitHandlerSafely:Z

.field public final redMemoryBufferSizeMultiplier:D

.field public final reduceMemoryDataSinkMemorySpike:Z

.field public final refreshManifestAfterInit:Z

.field public final refreshManifestOnPredictionRestriction:Z

.field public final releaseGrootSurfaceSync:Z

.field public final releaseHeroManagerWhenLowMemInBg:Z

.field public final releaseSurfaceBlockTimeoutMS:I

.field public final releaseSurfaceInServicePlayerReset:Z

.field public final releaseThreadInterval:I

.field public final removeGifPrefixForDRMKeyRequest:Z

.field public final renderRetryTimeMs:I

.field public final rendererAllowedJoiningTimeMs:J

.field public final reorderSeekPrepare:Z

.field public final reportExceptionAsMME:Z

.field public final reportExceptionsAsSoftErrors:Z

.field public final reportLastVideoInCrash:Z

.field public final reportPrefetchAbrDecision:Z

.field public final reportStallThresholdMs:I

.field public final reportStallThresholdMsLatencyManager:I

.field public final reportUnexpectedStopLoading:Z

.field public final resizeAndRepositionGrootSurfaceControl:Z

.field public final respectAbrForUll:Z

.field public final respectAbrIndexForUll:Z

.field public final respectDroppedQualityFlag:Z

.field public final respectDynamicPlayerSettings:Z

.field public final restartServiceThresholdMs:I

.field public final retryCountsForStartPlayManifest503:I

.field public final retryCountsForStartPlayManifestFetch:I

.field public final returnRequestedSeekTimeTimeoutMs:I

.field public final saturationFactor:F

.field public final scalingBufferErrorMs:I

.field public final sdKVersionToUseCustomizedBuffering:I

.field public final sdKVersionToUseTargetBufferOverwrite:I

.field public final sdkVersionToBypassHeroStateRefresh:I

.field public final sdkVersionToUseConservativeLoadControl:I

.field public final sdkVersionToUseDefaultLoadControl:I

.field public final secondPhasePrefetchQueueMaxSize:I

.field public final secondaryChannelLoggingMaxDisplayedFramesStringSize:I

.field public final secondaryChannelLoggingMaxNumOfFramesInOneJson:I

.field public final secondaryChannelLoggingSamplingFactor:I

.field public final seekParameterOptionIndex:I

.field public final segDurationMultiplier:I

.field public final serviceInjectorClassName:Ljava/lang/String;

.field public final setPlayWhenReadyOnError:Z

.field public final setPlayWhenReadyOnRetry:Z

.field public final shareBWEEstimateAcrossVideos:Z

.field public final shouldAddDefaultMP4Extractor:Z

.field public final shouldAlwaysDo503Retry:Z

.field public final shouldCleanupHeroManagerThread:Z

.field public final shouldDisableAV1VideoTrackOnlyforVDD:Z

.field public final shouldExcludeAbsolutePositionForClippingMediaSource:Z

.field public final shouldLoadBinaryDataFromManifest:Z

.field public final shouldLogInbandTelemetryBweDebugString:Z

.field public final shouldPrefetchSecondSegmentOffset:Z

.field public final shouldUseWarmupSlot:Z

.field public final shouldWarmupAwareOfAppScrolling:Z

.field public final showDebugStats:Z

.field public final skipAV1PreviousKeyFrameSeek:Z

.field public final skipAudioMediaCodecStopOnRelease:Z

.field public final skipAudioPrefetch:Z

.field public final skipDebugLogs:Z

.field public final skipEvaluateIflastChunkWasInitialization:Z

.field public final skipInlineManifestForLsbConfPercentile:I

.field public final skipInvalidSamples:Z

.field public final skipMediaCodecStopOnRelease:Z

.field public final skipPrefetchInCacheManager:Z

.field public final skipReleaseSurfaceBlock:Z

.field public final skipSurfaceViewReparentOnSetCurrentView:Z

.field public final skipSurfaceViewTransactionOnSameSurface:Z

.field public final skipSynchronizedUpdatePriority:Z

.field public final skipThumbnailCacheKey:Z

.field public final smallBandwidthCursorMs:I

.field public final smallBandwidthToleranceMs:I

.field public final smallJumpBandwidthMultiplier:F

.field public final smartGcEnabled:Z

.field public final smartGcTimeout:I

.field public final softErrorErrorCodeBlacklist:Ljava/util/Set;

.field public final softErrorErrorDomainBlacklist:Ljava/util/Set;

.field public final softErrorErrorMessageBlacklist:Ljava/util/Set;

.field public final sortSubripSubtitles:Z

.field public final splitBweOnRadio:Z

.field public final splitLastSegmentCachekey:Z

.field public final ssAbrAlphaDecay:F

.field public final ssAbrExperimentSetting:Ljava/lang/String;

.field public final ssAbrMinSamples:I

.field public final ssAbrNumSamplesAvg:I

.field public final staleManifestThreshold:I

.field public final staleManifestThresholdToShowInterruptUI:I

.field public final stallCountsToUpdateDynamicRebufferThreshold:I

.field public final stallFromSeekThresholdMs:I

.field public final stopRefreshingManifestNoPlaybackUpdateAfterTimeMs:I

.field public final streamLatencyToggleMaxSpeedDelta:F

.field public final streamLatencyTogglePIDDesiredBufferMs:I

.field public final streamLatencyTogglePIDIntegralBoundMs:I

.field public final streamLatencyToggleSpeedUpBandwidthMultiplier:F

.field public final streamLatencyToggleStateOverride:I

.field public final subtitleDurationToMaxValue:Z

.field public final surfaceControlForceVideoSizeUpdate:Z

.field public final surfaceMPDFailoverImmediately:Z

.field public final swallowSurfaceGlDetachError:Z

.field public final targetBufferBytesFactor:F

.field public final targetBytesForOverwrite:I

.field public final threadSleepMsForDecoderInitFailure:I

.field public final timeBetweenPIDSamplesMs:I

.field public final tslogSettings:LX/GRA;

.field public final unstallBufferSetting:LX/GRY;

.field public final unstallBufferSettingLive:LX/GRY;

.field public final updateConcatMsDuringPlayback:Z

.field public final updateLoadingPriorityExo2:Z

.field public final updateParamOnGetManifestFetcher:Z

.field public final updateUnstallBufferDuringPlayback:Z

.field public final useAccumulatorForBw:Z

.field public final useAdAwareLoadControl:Z

.field public final useAllSettingsToSupportLowerLatency:Z

.field public final useBackgroundHandlerForHeroLiveManager:Z

.field public final useBlockingSetSurfaceExo2:Z

.field public final useBufferBasedAbrPDash:Z

.field public final useBufferedCacheDataSink:Z

.field public final useBwBpsForConnectionQuality:Z

.field public final useCellMaxWaterMarkMsConfig:Z

.field public final useCodecNeedsEosBufferTimestampWorkaround:Z

.field public final useDefaultTrackSelector:Z

.field public final useDummySurfaceExo2:Z

.field public final useExoPlayerBuilder:Z

.field public final useFallbackLogging:Z

.field public final useForceSurfaceChange:Z

.field public final useFullscreenTransitionPrediction:Z

.field public final useHandlerThreadPool:Z

.field public final useHeroBufferSize:Z

.field public final useHttpPriorityIncrementalForLongBufferedStreaming:Z

.field public final useHttpPriorityIncrementalForPrefetch:Z

.field public final useHttpPriorityIncrementalForStreaming:Z

.field public final useHttpPriorityWarmupForLongBufferedStreaming:Z

.field public final useInterruptedIoException:Z

.field public final useIsCachedSkipInit:Z

.field public final useLatencyForSegmentConcat:Z

.field public final useLowPriorityForSecondPhasePrefetch:Z

.field public final useLowerHttpPriorityForAllPrefetch:Z

.field public final useLowerHttpPriorityForUnimportantPrefetch:Z

.field public final useMainThreadForHeroPlayer:Z

.field public final useMaxBufferForProgressive:Z

.field public final useMaxOfLowWatermarkOrPrevHighWaterMarkWhenForced:Z

.field public final useMediaCodecPoolingConcurrentCollections:Z

.field public final useMediaCodecPoolingForCodecByName:Ljava/lang/String;

.field public final useMinIntentBasedWatermarkBeforePlay:Z

.field public final useMultiPeriodBufferCalculation:Z

.field public final useNetworkAwareHttpPriorityIncrementalForStreaming:Z

.field public final useNetworkAwareSettingsForLargerChunk:Z

.field public final useNetworkAwareSettingsForUnstallBuffer:Z

.field public final useNetworkAwaretPrefetchTaskQueueWorkerNum:Z

.field public final useNonInterleavedExtractorForLocal:Z

.field public final useOutputSurfaceWorkaround:Z

.field public final usePerVideoLookupToCheckCache:Z

.field public final usePrefetchFilter:Z

.field public final usePrefetchSegmentOffset:Z

.field public final useSSAbrBWE:Z

.field public final useSSAbrMinRtt:Z

.field public final useShortKey:Z

.field public final useSimpleSpeedController:Z

.field public final useSingleCachedBandwidthEstimate:Z

.field public final useSsBweForVod:Z

.field public final useSteadyStateToControlSpeed:Z

.field public final useThreadSafeStandaloneClock:Z

.field public final useVersion2_18Workarounds:Z

.field public final useVideoSourceAsWarmupKey:Z

.field public final useWAPlayerPoolLoadControl:Z

.field public final useWatermarkEvaluatorForProgressive:Z

.field public final useWifiMaxWaterMarkMsConfig:Z

.field public final userAgent:Ljava/lang/String;

.field public final userId:Ljava/lang/String;

.field public final validateBytesToFallbackOnFirstSegment:Z

.field public final videoBufferSize:I

.field public final videoMemoryCacheSizeKb:I

.field public final videoPrefetchSetting:LX/GRF;

.field public final vp9BlockingReleaseSurface:Z

.field public final vp9PlaybackDecoderName:Ljava/lang/String;

.field public final wakelockOriginLists:Ljava/util/Set;

.field public final warmupAv1Codec:Z

.field public final warmupVp9Codec:Z

.field public final watchTimeThresholdToDisableFollowupPrefetch:F

.field public final watchTimeThresholdToDisableSecondPhasePrefetchSeconds:F

.field public final wifiMaxWatermarkMsConfig:LX/GRG;

.field public final xHEAACCEffectType:I

.field public final xHEAACTargetReferenceLvl:I


# direct methods
.method public static constructor <clinit>()V
    .locals 2

    new-instance v1, LX/FBk;

    invoke-direct {v1}, LX/FBk;-><init>()V

    new-instance v0, LX/GRl;

    invoke-direct {v0, v1}, LX/GRl;-><init>(LX/FBk;)V

    sput-object v0, LX/GRl;->A01:LX/GRl;

    new-instance v1, LX/Eoe;

    invoke-direct {v1}, Ljava/lang/Object;-><init>()V

    new-instance v0, Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

    invoke-direct {v0, v1}, Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;-><init>(LX/Eoe;)V

    sput-object v0, LX/GRl;->A00:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

    return-void
.end method

.method public constructor <init>(LX/FBk;)V
    .locals 3

    invoke-direct {p0}, Ljava/lang/Object;-><init>()V

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/GRl;->enableCacheNetworkTypeIfNotSet:Z

    iget-object v0, p1, LX/FBk;->A0O:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-object v0, p0, LX/GRl;->autogenSettings:Lcom/facebook/wa/video/heroplayer/setting/FbAutogeneratedSettings;

    iput-boolean v1, p0, LX/GRl;->improveLooping:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/GRl;->serviceInjectorClassName:Ljava/lang/String;

    iget v0, p1, LX/FBk;->A07:I

    iput v0, p0, LX/GRl;->playerPoolSize:I

    const/16 v0, 0x7d0

    iput v0, p0, LX/GRl;->releaseSurfaceBlockTimeoutMS:I

    iput-boolean v1, p0, LX/GRl;->skipReleaseSurfaceBlock:Z

    iget-object v0, p1, LX/FBk;->A0V:Ljava/lang/String;

    iput-object v0, p0, LX/GRl;->userAgent:Ljava/lang/String;

    const/4 v0, 0x0

    iput-object v0, p0, LX/GRl;->userId:Ljava/lang/String;

    const/16 v0, 0x14

    iput v0, p0, LX/GRl;->reportStallThresholdMs:I

    iput v0, p0, LX/GRl;->reportStallThresholdMsLatencyManager:I

    const/16 v0, 0xa

    iput v0, p0, LX/GRl;->checkPlayerStateMinIntervalMs:I

    const/16 v0, 0xc8

    iput v0, p0, LX/GRl;->checkPlayerStateMaxIntervalMs:I

    const/4 v0, 0x5

    iput v0, p0, LX/GRl;->checkPlayerStateIntervalIncreaseMs:I

    const/16 v0, 0xfa

    iput v0, p0, LX/GRl;->needUpdatePlayerStateThresholdMs:I

    const/16 v0, 0xa

    iput v0, p0, LX/GRl;->needUpdateStateByPositionOffsetThresholdMs:I

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->enablePauseNow:Z

    iput-boolean v1, p0, LX/GRl;->enableFBLiteHttpDataSource:Z

    iput-boolean v1, p0, LX/GRl;->useNonInterleavedExtractorForLocal:Z

    iput-boolean v1, p0, LX/GRl;->enableIgHttpDataSource:Z

    iput-boolean v1, p0, LX/GRl;->enableCaseInsensitiveHttpResponseHeaderKey:Z

    iput-boolean v1, p0, LX/GRl;->usePrefetchFilter:Z

    iput-boolean v1, p0, LX/GRl;->avoidServiceClassLoadOnClient:Z

    iput-boolean v1, p0, LX/GRl;->vp9BlockingReleaseSurface:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/GRl;->vp9PlaybackDecoderName:Ljava/lang/String;

    iput-boolean v1, p0, LX/GRl;->includeAllBufferingEvents:Z

    iget-object v0, p1, LX/FBk;->A0N:LX/GRK;

    iput-object v0, p0, LX/GRl;->cache:LX/GRK;

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->setPlayWhenReadyOnError:Z

    iput-boolean v0, p0, LX/GRl;->setPlayWhenReadyOnRetry:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/GRl;->returnRequestedSeekTimeTimeoutMs:I

    const/16 v0, 0x1f4

    iput v0, p0, LX/GRl;->stallFromSeekThresholdMs:I

    iput-boolean v1, p0, LX/GRl;->enablePrefetchCancelCallback:Z

    iget-object v0, p1, LX/FBk;->A0S:LX/GRY;

    iput-object v0, p0, LX/GRl;->unstallBufferSetting:LX/GRY;

    iget-object v0, p1, LX/FBk;->A0T:LX/GRY;

    iput-object v0, p0, LX/GRl;->unstallBufferSettingLive:LX/GRY;

    iput-boolean v1, p0, LX/GRl;->clearBufferingWhenInWarmup:Z

    iget-object v0, p1, LX/FBk;->A0P:LX/GRV;

    iput-object v0, p0, LX/GRl;->intentBasedBufferingConfig:LX/GRV;

    iput-boolean v1, p0, LX/GRl;->releaseSurfaceInServicePlayerReset:Z

    iput-boolean v1, p0, LX/GRl;->respectDynamicPlayerSettings:Z

    iput-boolean v1, p0, LX/GRl;->reportPrefetchAbrDecision:Z

    iget-object v0, p1, LX/FBk;->A0L:LX/K6x;

    iput-object v0, p0, LX/GRl;->abrSetting:LX/K6x;

    iget-object v0, p1, LX/FBk;->A0K:LX/GRj;

    iput-object v0, p0, LX/GRl;->predictiveDashSetting:LX/GRj;

    iput-boolean v1, p0, LX/GRl;->refreshManifestOnPredictionRestriction:Z

    iget-object v0, p1, LX/FBk;->A0J:LX/GRL;

    iput-object v0, p0, LX/GRl;->dynamicInfoSetting:LX/GRL;

    const/4 v0, 0x0

    iput-object v0, p0, LX/GRl;->mLowLatencySetting:LX/GR3;

    iput-object v0, p0, LX/GRl;->mEventLogSetting:LX/GR2;

    iget-object v0, p1, LX/FBk;->A0M:LX/GRC;

    iput-object v0, p0, LX/GRl;->audioLazyLoadSetting:LX/GRC;

    iput-boolean v1, p0, LX/GRl;->enableLazyAudioLoadForProgressive:Z

    iget-object v0, p1, LX/FBk;->A0U:LX/GRF;

    iput-object v0, p0, LX/GRl;->videoPrefetchSetting:LX/GRF;

    const/16 v0, 0x3023

    iput v0, p0, LX/GRl;->dashLowWatermarkMs:I

    const/16 v0, 0x3747

    iput v0, p0, LX/GRl;->dashHighWatermarkMs:I

    iput-boolean v1, p0, LX/GRl;->liveEnableStreamingCache:Z

    const-wide/16 v0, 0x7d0

    iput-wide v0, p0, LX/GRl;->minDelayToRefreshTigonBitrateMs:J

    const/4 v0, 0x0

    iput-object v0, p0, LX/GRl;->fetchCacheSourceHttpConnectTimeoutMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->fetchHttpReadTimeoutMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->concatenatedMsPerLoadConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->minBufferMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->minRebufferMsConfig:LX/GRG;

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/GRl;->enableGrootAlwaysSendPlayStarted:Z

    iput-object v0, p0, LX/GRl;->minMicroRebufferMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->liveMinBufferMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->liveMinRebufferMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->liveAPIMinBufferMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->liveAPIMinRebufferMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->livePremiumMinBufferMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->livePremiumMinRebufferMsConfig:LX/GRG;

    iput-boolean v1, p0, LX/GRl;->useLatencyForSegmentConcat:Z

    iget-object v0, p1, LX/FBk;->A0H:LX/GRG;

    iput-object v0, p0, LX/GRl;->latencyBoundMsConfig:LX/GRG;

    const/4 v0, 0x0

    iput-object v0, p0, LX/GRl;->fbstoriesMinBufferMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->fbstoriesMinRebufferMsConfig:LX/GRG;

    iget-object v0, p1, LX/FBk;->A0I:LX/GRG;

    iput-object v0, p0, LX/GRl;->qualityMapperBoundMsConfig:LX/GRG;

    iput-boolean v1, p0, LX/GRl;->enableProgressiveFallbackWhenNoRepresentations:Z

    iput-boolean v1, p0, LX/GRl;->blockDRMPlaybackOnHDMI:Z

    iput-boolean v1, p0, LX/GRl;->blockDRMScreenCapture:Z

    iput-boolean v1, p0, LX/GRl;->fixDRMPlaybackOnHDMI:Z

    iput-boolean v1, p0, LX/GRl;->enableWarmCodec:Z

    const/4 v0, 0x2

    iput v0, p0, LX/GRl;->playerWarmUpPoolSize:I

    const/16 v0, 0x3e8

    iput v0, p0, LX/GRl;->playerWatermarkBeforePlayedMs:I

    iput v0, p0, LX/GRl;->playerWarmUpWatermarkMs:I

    iput-boolean v1, p0, LX/GRl;->allowOverridingPlayerWarmUpWatermark:Z

    iput-boolean v1, p0, LX/GRl;->swallowSurfaceGlDetachError:Z

    iput-boolean v1, p0, LX/GRl;->forceMainThreadHandlerForHeroSurface:Z

    iput-boolean v1, p0, LX/GRl;->enableWarmupScheduler:Z

    iput-boolean v1, p0, LX/GRl;->enableWarmupSkipScheduler:Z

    iput-boolean v1, p0, LX/GRl;->enableWarmupSchedulerRightAway:Z

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/GRl;->rendererAllowedJoiningTimeMs:J

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/GRl;->skipPrefetchInCacheManager:Z

    iput-boolean v1, p0, LX/GRl;->useNetworkAwareSettingsForLargerChunk:Z

    iput-boolean v1, p0, LX/GRl;->enableDebugLogs:Z

    iput-boolean v1, p0, LX/GRl;->skipDebugLogs:Z

    iput-boolean v1, p0, LX/GRl;->showDebugStats:Z

    iput-boolean v1, p0, LX/GRl;->isAbrTracingEnabled:Z

    iget-boolean v0, p1, LX/FBk;->A0f:Z

    iput-boolean v0, p0, LX/GRl;->dummyDefaultSetting:Z

    iput-boolean v1, p0, LX/GRl;->enableCachedBandwidthEstimate:Z

    iput-boolean v1, p0, LX/GRl;->useSingleCachedBandwidthEstimate:Z

    iput-boolean v1, p0, LX/GRl;->disableTigonBandwidthLogging:Z

    iput-boolean v1, p0, LX/GRl;->shouldLogInbandTelemetryBweDebugString:Z

    iput-boolean v1, p0, LX/GRl;->killVideoProcessWhenMainProcessDead:Z

    iput-boolean v1, p0, LX/GRl;->isLiveTraceEnabled:Z

    iput-boolean v1, p0, LX/GRl;->isTATracingEnabled:Z

    iput-boolean v1, p0, LX/GRl;->releaseGrootSurfaceSync:Z

    iput-boolean v1, p0, LX/GRl;->asyncReleaseSurfaceOnMainThread:Z

    iput-boolean v1, p0, LX/GRl;->preventTextRendererDelay:Z

    iput-boolean v1, p0, LX/GRl;->fixPeriodTransitionWithNonZeroStartPosition:Z

    iput-boolean v1, p0, LX/GRl;->abrMonitorEnabled:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/GRl;->maxNumGapsToNotify:I

    iput-boolean v1, p0, LX/GRl;->enableMediaCodecPoolingForVodVideo:Z

    iput-boolean v1, p0, LX/GRl;->enableMediaCodecPoolingForVodAudio:Z

    iput-boolean v1, p0, LX/GRl;->enableMediaCodecPoolingForLiveVideo:Z

    iput-boolean v1, p0, LX/GRl;->enableMediaCodecPoolingForLiveAudio:Z

    iput-boolean v1, p0, LX/GRl;->enableMediaCodecPoolingForProgressiveVideo:Z

    iput-boolean v1, p0, LX/GRl;->enableMediaCodecPoolingForProgressiveAudio:Z

    iput-boolean v1, p0, LX/GRl;->enableMediaCodecReuseOptimizeLock:Z

    iput-boolean v1, p0, LX/GRl;->enableMediaCodecReuseOptimizeRelease:Z

    iput-boolean v1, p0, LX/GRl;->useMediaCodecPoolingConcurrentCollections:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/GRl;->useMediaCodecPoolingForCodecByName:Ljava/lang/String;

    iput-boolean v1, p0, LX/GRl;->useVersion2_18Workarounds:Z

    iput-boolean v1, p0, LX/GRl;->useCodecNeedsEosBufferTimestampWorkaround:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/GRl;->releaseThreadInterval:I

    const/4 v0, 0x2

    iput v0, p0, LX/GRl;->maxMediaCodecInstancesPerCodecName:I

    const/4 v0, 0x4

    iput v0, p0, LX/GRl;->maxMediaCodecInstancesTotal:I

    iput-boolean v1, p0, LX/GRl;->enableAlwaysCallPreallocateCodec:Z

    iput-boolean v1, p0, LX/GRl;->isEarlyPreallocateCodec:Z

    iput-boolean v1, p0, LX/GRl;->earlyPreallocateCodecOnAppNotScrolling:Z

    iput-boolean v1, p0, LX/GRl;->earlyPreallocateCodecOnIdle:Z

    iput-boolean v1, p0, LX/GRl;->disablePreallocateCodecDuringStartup:Z

    iput-boolean v1, p0, LX/GRl;->useNetworkAwareSettingsForUnstallBuffer:Z

    iput-boolean v1, p0, LX/GRl;->disableStoriesCustomizedUnstallBuffer:Z

    iput-boolean v1, p0, LX/GRl;->bgHeroServiceStatusUpdate:Z

    iput-boolean v1, p0, LX/GRl;->isExo2UseAbsolutePosition:Z

    iput-boolean v1, p0, LX/GRl;->shouldExcludeAbsolutePositionForClippingMediaSource:Z

    iput-boolean v1, p0, LX/GRl;->isExo2MediaCodecReuseEnabled:Z

    iput-boolean v1, p0, LX/GRl;->useBlockingSetSurfaceExo2:Z

    iput-boolean v1, p0, LX/GRl;->isExo2AggresiveMicrostallFixEnabled:Z

    iput-boolean v1, p0, LX/GRl;->warmupVp9Codec:Z

    iput-boolean v1, p0, LX/GRl;->warmupAv1Codec:Z

    iget-boolean v0, p1, LX/FBk;->A0i:Z

    iput-boolean v0, p0, LX/GRl;->playerRespawnExo2:Z

    iput-boolean v1, p0, LX/GRl;->updateLoadingPriorityExo2:Z

    iput-boolean v1, p0, LX/GRl;->checkReadToEndBeforeUpdatingFinalState:Z

    iput-boolean v1, p0, LX/GRl;->isExo2Vp9Enabled:Z

    iput-boolean v1, p0, LX/GRl;->exo2Vp9UseSurfaceRenderer:Z

    iput-boolean v1, p0, LX/GRl;->skipEvaluateIflastChunkWasInitialization:Z

    iput-boolean v1, p0, LX/GRl;->logOnApacheFallback:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->enableSystrace:Z

    iput-boolean v1, p0, LX/GRl;->isDefaultMC:Z

    const-string v0, "unset"

    iput-object v0, p0, LX/GRl;->mcDebugState:Ljava/lang/String;

    iput-object v0, p0, LX/GRl;->mcValueSource:Ljava/lang/String;

    iput-boolean v1, p0, LX/GRl;->enableCodecPreallocation:Z

    iput-boolean v1, p0, LX/GRl;->enableVp9CodecPreallocation:Z

    iput-boolean v1, p0, LX/GRl;->preventPreallocateIfNotEmpty:Z

    iput-boolean v1, p0, LX/GRl;->enableRequestEtdHeader:Z

    iput-boolean v1, p0, LX/GRl;->reportLastVideoInCrash:Z

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/GRl;->maxDurationUsForFullSegmentPrefetch:J

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/GRl;->isSetSerializableBlacklisted:Z

    iput-boolean v1, p0, LX/GRl;->useWatermarkEvaluatorForProgressive:Z

    iput-boolean v1, p0, LX/GRl;->useMaxBufferForProgressive:Z

    iget-boolean v0, p1, LX/FBk;->A0l:Z

    iput-boolean v0, p0, LX/GRl;->useDummySurfaceExo2:Z

    iput-boolean v1, p0, LX/GRl;->useVideoSourceAsWarmupKey:Z

    const-wide/32 v0, 0x5b8d80

    iput-wide v0, p0, LX/GRl;->maxBufferDurationPausedLiveUs:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableUsingASRCaptions:Z

    iput-boolean v0, p0, LX/GRl;->enableBitrateAwareAudioPrefetch:Z

    iput-boolean v0, p0, LX/GRl;->proxyDrmProvisioningRequests:Z

    iput-boolean v0, p0, LX/GRl;->liveUseLowPriRequests:Z

    const/16 v0, 0xfa0

    iput v0, p0, LX/GRl;->liveDashEdgeLatencyMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->logLatencyEvents:Z

    iput-boolean v0, p0, LX/GRl;->disableLatencyManagerOnStaticManifest:Z

    iput-boolean v0, p0, LX/GRl;->enablePreSeekToApi:Z

    iput-boolean v0, p0, LX/GRl;->continuouslyLoadFromPreSeekLocation:Z

    const-wide v0, 0x7fffffffffffffffL

    iput-wide v0, p0, LX/GRl;->minBufferForPreSeekMs:J

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->audioVideoSyncPeriodMs:I

    iput-boolean v0, p0, LX/GRl;->enableProgressivePrefetchWhenNoRepresentations:Z

    iput-boolean v0, p0, LX/GRl;->continueLoadingOnSeekbarExo2:Z

    iput-boolean v0, p0, LX/GRl;->subtitleDurationToMaxValue:Z

    iput-boolean v0, p0, LX/GRl;->isExo2DrmEnabled:Z

    iput-boolean v0, p0, LX/GRl;->enableDrmProvisioningRetry:Z

    iput-boolean v0, p0, LX/GRl;->sortSubripSubtitles:Z

    iput-boolean v0, p0, LX/GRl;->logStallOnPauseOnError:Z

    iput-boolean v0, p0, LX/GRl;->skipSynchronizedUpdatePriority:Z

    iput-boolean v0, p0, LX/GRl;->exo2ReuseManifestAfterInitialParse:Z

    iput-boolean v0, p0, LX/GRl;->enableFrameBasedLogging:Z

    const/16 v0, 0x64

    iput v0, p0, LX/GRl;->prefetchTaskQueueSize:I

    const/4 v0, 0x1

    iput v0, p0, LX/GRl;->prefetchTaskQueueWorkerNum:I

    const/4 v0, 0x2

    iput v0, p0, LX/GRl;->prefetchUrgentTaskQueueWorkerNum:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->usePrefetchSegmentOffset:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->refreshManifestAfterInit:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->disableAudioFocusInGroot:Z

    iput-boolean v0, p0, LX/GRl;->offloadGrootAudioFocus:Z

    iput-boolean v0, p0, LX/GRl;->enableDeduplicateImfEmsgAtPlayer:Z

    const/16 v0, 0xfa0

    iput v0, p0, LX/GRl;->numMsToPrefetch:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableWifiLongerPrefetchAds:Z

    iput-boolean v0, p0, LX/GRl;->enableAllLongerPrefetchAds:Z

    const/4 v0, -0x1

    iput v0, p0, LX/GRl;->maxWifiPrefetchDurationMsAds:I

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->adBreakEnahncedPrefetchDurationMs:I

    iput-boolean v0, p0, LX/GRl;->enableAdBreakEnhancedPrefetch:Z

    const/high16 v0, 0x100000

    iput v0, p0, LX/GRl;->maxWifiBytesToPrefetchAds:I

    const/4 v0, -0x1

    iput v0, p0, LX/GRl;->minLiveStartPositionMs:I

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->stopRefreshingManifestNoPlaybackUpdateAfterTimeMs:I

    const/16 v0, 0x2ee0

    iput v0, p0, LX/GRl;->liveDashHighWatermarkMs:I

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->liveDashLowWatermarkMs:I

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->prefetchTaskQueuePutInFront:Z

    iput v0, p0, LX/GRl;->prefetchTaskQueueRetryNumber:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableCancelOngoingRequestPause:Z

    iput-boolean v0, p0, LX/GRl;->shouldPrefetchSecondSegmentOffset:Z

    iput-boolean v0, p0, LX/GRl;->fallbackToFirstSegment:Z

    iput-boolean v0, p0, LX/GRl;->enableSegmentIndexCheckForPrefetchBytes:Z

    iput-boolean v0, p0, LX/GRl;->validateBytesToFallbackOnFirstSegment:Z

    const-string v2, ""

    iput-object v2, p0, LX/GRl;->prefetchTagBlockList:Ljava/lang/String;

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->enabledViewManagementInGroot:Z

    const/high16 v0, 0x20000

    iput v0, p0, LX/GRl;->maxBytesToPrefetchVOD:I

    const/high16 v0, 0x10000

    iput v0, p0, LX/GRl;->maxBytesToPrefetchCellVOD:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableLiveOneTimeLoadingJump:Z

    iput-boolean v0, p0, LX/GRl;->enableSpatialOpusRendererExo2:Z

    iput-boolean v0, p0, LX/GRl;->manifestErrorReportingExo2:Z

    iput-boolean v0, p0, LX/GRl;->manifestMisalignmentReportingExo2:Z

    iput-boolean v0, p0, LX/GRl;->enableVideoHybridCache:Z

    iput-boolean v0, p0, LX/GRl;->enableHybridCacheForPrefetch:Z

    iput-boolean v0, p0, LX/GRl;->enableVideoMemoryCache:Z

    const v0, 0x18aa0

    iput v0, p0, LX/GRl;->videoMemoryCacheSizeKb:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->alwaysPerformContentLengthUpdateFirst:Z

    iput-boolean v0, p0, LX/GRl;->enableUpdateProgressiveContentLengthFromCache:Z

    iput-boolean v0, p0, LX/GRl;->enableLongCacheKeyForContentLength:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->updateParamOnGetManifestFetcher:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->prefetchBypassFilter:Z

    iput-boolean v0, p0, LX/GRl;->useBufferBasedAbrPDash:Z

    const/4 v0, 0x5

    iput v0, p0, LX/GRl;->minimumLogLevel:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->isMeDevice:Z

    iput-boolean v0, p0, LX/GRl;->enableOffloadingIPC:Z

    iput-boolean v0, p0, LX/GRl;->pausePlayingVideoWhenRelease:Z

    iput-boolean v0, p0, LX/GRl;->enableAv1Dav1d:Z

    iput-boolean v0, p0, LX/GRl;->enableAv1LibGav1:Z

    iput-boolean v0, p0, LX/GRl;->prioritizeAv1HardwareDecoder:Z

    iget-object v0, p1, LX/FBk;->A0W:Ljava/util/HashMap;

    iput-object v0, p0, LX/GRl;->blockListedHardwareDecoderMap:Ljava/util/HashMap;

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->prioritizeAv1Dav1dOverLibgav1:Z

    iput v0, p0, LX/GRl;->dav1dThreads:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->handleReleasedReusedSurfaceTexture:Z

    const/4 v0, 0x1

    iput v0, p0, LX/GRl;->dav1dMaxFrameDelay:I

    iput-boolean v0, p0, LX/GRl;->dav1dApplyGrain:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->av1SetBuffersDataspace:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->av1UseMemoryCleanupFixes:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->av1UseDav1dSynchronizationFixes:Z

    iput-boolean v0, p0, LX/GRl;->av1FlushDav1dProperly:Z

    iput-boolean v0, p0, LX/GRl;->useForceSurfaceChange:Z

    iput-boolean v0, p0, LX/GRl;->parseAndAttachETagManifest:Z

    iput-boolean v0, p0, LX/GRl;->enableSecondPhasePrefetch:Z

    iput-boolean v0, p0, LX/GRl;->disableSecondPhasePrefetchForReels:Z

    iput-boolean v0, p0, LX/GRl;->disableSecondPhasePrefetchForDataSaver:Z

    iput-boolean v0, p0, LX/GRl;->enableSecondPhasePrefetchWebm:Z

    iput-boolean v0, p0, LX/GRl;->disableSecondPhasePrefetchOnAppScrolling:Z

    iput-boolean v0, p0, LX/GRl;->enableSecondPhaseAlignment:Z

    iput v0, p0, LX/GRl;->secondPhasePrefetchQueueMaxSize:I

    iput v0, p0, LX/GRl;->numSegmentsToSecondPhasePrefetch:I

    iput v0, p0, LX/GRl;->numSegmentsToSecondPhasePrefetchAudio:I

    iput v0, p0, LX/GRl;->numSegmentsToSecondPhasePrefetchXHEAACAudio:I

    iput-boolean v0, p0, LX/GRl;->enableLogSemiCachedEvents:Z

    iput-boolean v0, p0, LX/GRl;->enableCacheBlockWithoutTimeout:Z

    iput-boolean v0, p0, LX/GRl;->enableLogExceptionMessageOnError:Z

    iput-boolean v0, p0, LX/GRl;->reportExceptionsAsSoftErrors:Z

    iput-boolean v0, p0, LX/GRl;->reportExceptionAsMME:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->checkCachedLockedCacheSpan:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->prefetchAudioFirst:Z

    iput-boolean v0, p0, LX/GRl;->cancelOngoingRequest:Z

    iput-boolean v0, p0, LX/GRl;->enableCancelPrefetchInQueuePrepare:Z

    iput-boolean v0, p0, LX/GRl;->enableBoostOngoingPrefetchPriorityPrepare:Z

    iput-boolean v0, p0, LX/GRl;->enableBoostOngoingPrefetchPriorityPlay:Z

    iput-boolean v0, p0, LX/GRl;->enableDemoteOngoingPrefetchPriorityPause:Z

    iput-boolean v0, p0, LX/GRl;->enableCancelOngoingPrefetchPause:Z

    iput-boolean v0, p0, LX/GRl;->enableCancelFollowupPrefetch:Z

    iput-boolean v0, p0, LX/GRl;->prefetchAudioFirstForStoriesAds:Z

    iput-boolean v0, p0, LX/GRl;->skipAudioPrefetch:Z

    iput-boolean v0, p0, LX/GRl;->allowOutOfBoundsAccessForPDash:Z

    iput v0, p0, LX/GRl;->minNumManifestForOutOfBoundsPDash:I

    iput-boolean v0, p0, LX/GRl;->enableNeedCenteringIndependentlyGroot:Z

    iput-boolean v0, p0, LX/GRl;->av1ThrowExceptionOnPictureError:Z

    iput-boolean v0, p0, LX/GRl;->av1ThrowExceptionOnNonDav1dDecoder:Z

    iget-wide v0, p1, LX/FBk;->A0G:J

    iput-wide v0, p0, LX/GRl;->ignoreStreamErrorsTimeoutMs:J

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/GRl;->ignoreLiveStreamErrorsTimeoutMs:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->callbackFirstCaughtStreamError:Z

    iput-boolean v0, p0, LX/GRl;->avoidSecondPhaseOnCell:Z

    iput-boolean v0, p0, LX/GRl;->includeLiveTraceHeader:Z

    iput-boolean v0, p0, LX/GRl;->alwaysReuseManifestFetcher:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->av1Dav1dEnableVpsLogging:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->av1Dav1dUseSurfaceViewSetFix:Z

    iput-boolean v0, p0, LX/GRl;->skipSurfaceViewReparentOnSetCurrentView:Z

    iput-boolean v0, p0, LX/GRl;->skipSurfaceViewTransactionOnSameSurface:Z

    iput-boolean v0, p0, LX/GRl;->allowMultiPlayerFormatWarmup:Z

    iput-boolean v0, p0, LX/GRl;->reorderSeekPrepare:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->prioritizeTimeOverSizeThresholds:Z

    iput-boolean v0, p0, LX/GRl;->livePrioritizeTimeOverSizeThresholds:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->disableCapBufferSizeLocalProgressive:Z

    iput-boolean v0, p0, LX/GRl;->useHeroBufferSize:Z

    iput v0, p0, LX/GRl;->videoBufferSize:I

    iput v0, p0, LX/GRl;->audioBufferSize:I

    iput-boolean v0, p0, LX/GRl;->enableMemoryAwareBufferSizeUsingRed:Z

    iput-boolean v0, p0, LX/GRl;->enableMemoryAwareBufferSizeUsingYellow:Z

    const-wide/high16 v0, 0x3ff0000000000000L    # 1.0

    iput-wide v0, p0, LX/GRl;->redMemoryBufferSizeMultiplier:D

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->useAccumulatorForBw:Z

    iput-boolean v0, p0, LX/GRl;->parseManifestIdentifier:Z

    iput-boolean v0, p0, LX/GRl;->enableCDNDebugHeaders:Z

    const/4 v0, -0x1

    iput v0, p0, LX/GRl;->maxTimeMsSinceRefreshPDash:I

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->predictionMaxSegmentDurationMs:I

    const/16 v0, 0x2134

    iput v0, p0, LX/GRl;->predictiveDashReadTimeoutMs:I

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->segDurationMultiplier:I

    const/16 v0, 0x1f40

    iput v0, p0, LX/GRl;->predictedHuddleDashManifestReadTimeoutMs:I

    iput v0, p0, LX/GRl;->predictedLiveDashManifestReadTimeoutMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableServerSideAbr:Z

    iput-boolean v0, p0, LX/GRl;->enableServerSideForwardBwe:Z

    iput-boolean v0, p0, LX/GRl;->useSSAbrBWE:Z

    iput-boolean v0, p0, LX/GRl;->useSSAbrMinRtt:Z

    iput-boolean v0, p0, LX/GRl;->useSsBweForVod:Z

    iput-boolean v0, p0, LX/GRl;->enableSsBweHeaderForLive:Z

    iput-boolean v0, p0, LX/GRl;->shareBWEEstimateAcrossVideos:Z

    iput-boolean v0, p0, LX/GRl;->splitBweOnRadio:Z

    const v0, 0x7a120

    iput v0, p0, LX/GRl;->progressivePrefetchBytesWifi:I

    const v0, 0x3e800

    iput v0, p0, LX/GRl;->progressivePrefetchBytesCell:I

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->maxSegmentsToPredict:I

    iput-boolean v0, p0, LX/GRl;->getMinLoadPositionStartOfPlayback:Z

    const v0, 0x3f4ccccd

    iput v0, p0, LX/GRl;->largeJumpBandwidthMultiplier:F

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/GRl;->smallJumpBandwidthMultiplier:F

    const/16 v0, 0x7d0

    iput v0, p0, LX/GRl;->highJumpDistanceMs:I

    const/16 v0, 0x1f40

    iput v0, p0, LX/GRl;->lowJumpDistanceMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableDynamicDiscontinuityDistance:Z

    const/16 v0, 0xfa0

    iput v0, p0, LX/GRl;->dynamicDiscontinuityInitialPosMs:I

    const/4 v0, 0x3

    iput v0, p0, LX/GRl;->maxStaleManifestCountForDiscontinuityJumps:I

    const/16 v0, 0x7d0

    iput v0, p0, LX/GRl;->minTimeBetweenDynamicCursorChangesMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableDynamicCursorDistance:Z

    const/16 v0, 0x7d0

    iput v0, p0, LX/GRl;->largeBandwidthCursorMs:I

    const/16 v0, 0xfa0

    iput v0, p0, LX/GRl;->smallBandwidthCursorMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/GRl;->largeBandwidthToleranceMs:I

    iput v0, p0, LX/GRl;->smallBandwidthToleranceMs:I

    const/16 v0, 0x3c

    iput v0, p0, LX/GRl;->minimumTimeBetweenStallsS:I

    const/16 v0, 0x1e

    iput v0, p0, LX/GRl;->minimumTimeBetweenSpeedChangesS:I

    const/4 v0, 0x5

    iput v0, p0, LX/GRl;->minTimeBetweenStallToIgnoreDiscontJumpS:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->ignoreTemplatedMinLoadPosition:Z

    iput-boolean v0, p0, LX/GRl;->preventJumpStaticManifest:Z

    iput-boolean v0, p0, LX/GRl;->maybeSkipInlineManifestForLSB:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->disableSkipInlineForHuddle:Z

    const/16 v0, 0x4b

    iput v0, p0, LX/GRl;->skipInlineManifestForLsbConfPercentile:I

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/GRl;->bandwidthMultiplierToSkipPrefetchedContent:F

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->maxTimeToSkipInlineManifestMs:I

    iput v0, p0, LX/GRl;->minTimeToSkipInlineManifestMs:I

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/GRl;->aggressiveEdgeLatencyOverrideForLSB:J

    const/16 v0, 0x4b

    iput v0, p0, LX/GRl;->aggressiveEdgeLatencyForLsbConfPercentile:I

    const/high16 v0, 0x3f000000    # 0.5f

    iput v0, p0, LX/GRl;->bandwidthMultiplierForAggressiveEdgeLatency:F

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableLatencyPlaybackSpeed:Z

    iput-boolean v0, p0, LX/GRl;->useSimpleSpeedController:Z

    iput-boolean v0, p0, LX/GRl;->useSteadyStateToControlSpeed:Z

    const v0, 0x3f866666

    iput v0, p0, LX/GRl;->expBackOffSpeedUp:F

    const/high16 v0, -0x40800000    # -1.0f

    iput v0, p0, LX/GRl;->watchTimeThresholdToDisableFollowupPrefetch:F

    const/high16 v0, 0x3f000000    # 0.5f

    iput v0, p0, LX/GRl;->pidMultiplierFloor:F

    const v0, 0x3f99999a

    iput v0, p0, LX/GRl;->pidParameterMultiplierInitial:F

    const v0, 0x3f733333

    iput v0, p0, LX/GRl;->pidParameterExpBackOff:F

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableLiveLatencyManager:Z

    iput-boolean v0, p0, LX/GRl;->enableLiveJumpByTrimBuffer:Z

    iput-boolean v0, p0, LX/GRl;->enableLatencyManagerRateLimiting:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->forceSeekRushPlayback:Z

    iput-object v2, p0, LX/GRl;->liveLatencyManagerPlayerFormat:Ljava/lang/String;

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableLiveBufferMeter:Z

    iput-boolean v0, p0, LX/GRl;->enableLiveBWEstimation:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/GRl;->liveTrimByBufferMeterMinDeltaMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableAvc1ColorConfigParseFix:Z

    const/16 v0, 0x14

    iput v0, p0, LX/GRl;->liveBufferDurationFluctuationTolerancePercent:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->liveBufferMeterTrimByMinBuffer:Z

    iput-boolean v0, p0, LX/GRl;->enableSuspensionAfterBroadcasterStall:Z

    iput-boolean v0, p0, LX/GRl;->allowImmediateLiveBufferTrim:Z

    const/16 v0, 0x1388

    iput v0, p0, LX/GRl;->initialBufferTrimPeriodMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/GRl;->initialBufferTrimThresholdMs:I

    const/16 v0, 0xfa0

    iput v0, p0, LX/GRl;->initialBufferTrimTargetMs:I

    iput v0, p0, LX/GRl;->extendedLiveRebufferThresholdMs:I

    iput v0, p0, LX/GRl;->allowedExtendedRebufferPeriodMs:I

    const/16 v0, 0x7530

    iput v0, p0, LX/GRl;->frequentBroadcasterStallIntervalThresholdMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/GRl;->extendedPremiumTierLiveRebufferThresholdMs:I

    const/16 v0, 0x2710

    iput v0, p0, LX/GRl;->allowedExtendedPremiumTierRebufferPeriodMs:I

    const v0, 0xea60

    iput v0, p0, LX/GRl;->frequentPremiumTierBroadcasterStallIntervalThresholdMs:I

    const/16 v0, 0x1770

    iput v0, p0, LX/GRl;->extendedApiTierLiveRebufferThresholdMs:I

    const v0, 0xea60

    iput v0, p0, LX/GRl;->frequentApiTierBroadcasterStallIntervalThresholdMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableLiveTierSpecificRebuffer:Z

    iput-boolean v0, p0, LX/GRl;->enableMP3Extractor:Z

    iput-boolean v0, p0, LX/GRl;->enableMp3Mp4ExtractorLogic:Z

    const/4 v0, -0x1

    iput v0, p0, LX/GRl;->maxNumRedirects:I

    const-string v0, "FB4A/Facebook"

    iput-object v0, p0, LX/GRl;->defaultUserAgent:Ljava/lang/String;

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->splitLastSegmentCachekey:Z

    iput-boolean v0, p0, LX/GRl;->enableEmsgPtsAlignment:Z

    const/4 v0, 0x1

    iput v0, p0, LX/GRl;->fragmentedMp4ExtractorVersion:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enablePlayerActionStateLoggingInFlytrap:Z

    iput-boolean v0, p0, LX/GRl;->enableWarmUpRequestOffscreen:Z

    iput-boolean v0, p0, LX/GRl;->enableFirstWarmUpRequestOnScreen:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->newDownstreamFormatChange:Z

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->microStallThresholdMsToUseMinBuffer:I

    iput-boolean v0, p0, LX/GRl;->updateUnstallBufferDuringPlayback:Z

    iput-boolean v0, p0, LX/GRl;->updateConcatMsDuringPlayback:Z

    iput-boolean v0, p0, LX/GRl;->enableVodDrmPrefetch:Z

    iput-boolean v0, p0, LX/GRl;->enableActiveDrmSessionStoreRelease:Z

    const/4 v0, 0x3

    iput v0, p0, LX/GRl;->drmSessionStoreCapacity:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableCustomizedXHEAACConfig:Z

    iput-boolean v0, p0, LX/GRl;->enableSeamlessAudioCodecAdaptation:Z

    iput-boolean v0, p0, LX/GRl;->enableCustomizedDRCEffect:Z

    iput-boolean v0, p0, LX/GRl;->enableCustomizedDRCForHeadset:Z

    const/16 v0, 0x12

    iput v0, p0, LX/GRl;->lateNightHourLowerThreshold:I

    const/4 v0, 0x6

    iput v0, p0, LX/GRl;->lateNightHourUpperThreshold:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableAsynchronousBufferQueueing:Z

    iput-boolean v0, p0, LX/GRl;->enableSynchronizeCodecInteractionsWithQueueing:Z

    iput-boolean v0, p0, LX/GRl;->enableLowLatencyDecoding:Z

    iput-boolean v0, p0, LX/GRl;->enableLowLatencyDecodingOverrideSDKGating:Z

    const/16 v0, 0x40

    iput v0, p0, LX/GRl;->xHEAACTargetReferenceLvl:I

    const/4 v0, 0x3

    iput v0, p0, LX/GRl;->xHEAACCEffectType:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->useBwBpsForConnectionQuality:Z

    iput-boolean v0, p0, LX/GRl;->preventWarmupInvalidSource:Z

    iput-boolean v0, p0, LX/GRl;->reportUnexpectedStopLoading:Z

    iput-boolean v0, p0, LX/GRl;->enableReduceRetryBeforePlay:Z

    const/4 v0, 0x1

    iput v0, p0, LX/GRl;->minRetryCountBeforePlay:I

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/GRl;->forceMinWatermarkGreaterThanMinRebuffer:Z

    iput-boolean v1, p0, LX/GRl;->bypassGreaterThanMinRebufferWhenBeforePlay:Z

    iput-boolean v1, p0, LX/GRl;->useMaxOfLowWatermarkOrPrevHighWaterMarkWhenForced:Z

    iput-boolean v1, p0, LX/GRl;->useWifiMaxWaterMarkMsConfig:Z

    iput-boolean v1, p0, LX/GRl;->useCellMaxWaterMarkMsConfig:Z

    iput-boolean v1, p0, LX/GRl;->useNetworkAwaretPrefetchTaskQueueWorkerNum:Z

    const/4 v0, 0x0

    iput-object v0, p0, LX/GRl;->wifiMaxWatermarkMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->cellMaxWatermarkMsConfig:LX/GRG;

    iput-object v0, p0, LX/GRl;->networkAwareDisableSecondPhasePrefetch:LX/GRG;

    iput-object v0, p0, LX/GRl;->networkAwarePrefetchTaskQueueWorkerNum:LX/GRG;

    iput-object v0, p0, LX/GRl;->networkAwareHttpPriorityIncrementalForStreaming:LX/GRG;

    iput-boolean v1, p0, LX/GRl;->skipInvalidSamples:Z

    iput v1, p0, LX/GRl;->minBufferedDurationMsToCancel:I

    iput v1, p0, LX/GRl;->decoderInitializationRetryTimeMs:I

    iput v1, p0, LX/GRl;->decoderDequeueRetryTimeMs:I

    iput v1, p0, LX/GRl;->renderRetryTimeMs:I

    iput-boolean v1, p0, LX/GRl;->disableRecoverInBackground:Z

    iput-boolean v1, p0, LX/GRl;->enableEnsureBindService:Z

    iput-boolean v1, p0, LX/GRl;->enableFallbackToMainProcess:Z

    iput-boolean v1, p0, LX/GRl;->enableKillProcessBeforeRebind:Z

    iput v1, p0, LX/GRl;->restartServiceThresholdMs:I

    iput-boolean v1, p0, LX/GRl;->fixSurfaceInvisibleParent:Z

    iput v1, p0, LX/GRl;->depthTocheckSurfaceInvisibleParent:I

    iput-boolean v1, p0, LX/GRl;->isAudioDataSummaryEnabled:Z

    iput-boolean v1, p0, LX/GRl;->enableBlackscreenDetector:Z

    const-wide/16 v0, 0x7d0

    iput-wide v0, p0, LX/GRl;->blackscreenSampleIntervalMs:J

    const-wide/16 v0, 0x3e8

    iput-wide v0, p0, LX/GRl;->blackscreenNoSampleThresholdMs:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->blackscreenDetectOnce:Z

    iput-boolean v0, p0, LX/GRl;->fixBlackscreenByRecreatingSurface:Z

    iput-boolean v0, p0, LX/GRl;->removeGifPrefixForDRMKeyRequest:Z

    iput-boolean v0, p0, LX/GRl;->enableDrmSessionStore:Z

    iput-boolean v0, p0, LX/GRl;->skipMediaCodecStopOnRelease:Z

    iget-object v0, p1, LX/FBk;->A0b:Ljava/util/Set;

    iput-object v0, p0, LX/GRl;->softErrorErrorDomainBlacklist:Ljava/util/Set;

    iget-object v0, p1, LX/FBk;->A0a:Ljava/util/Set;

    iput-object v0, p0, LX/GRl;->softErrorErrorCodeBlacklist:Ljava/util/Set;

    iget-object v0, p1, LX/FBk;->A0c:Ljava/util/Set;

    iput-object v0, p0, LX/GRl;->softErrorErrorMessageBlacklist:Ljava/util/Set;

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->logPausedSeekPositionBeforeSettingState:Z

    iput-boolean v0, p0, LX/GRl;->enableRetryWarmup:Z

    const/16 v0, 0x64

    iput v0, p0, LX/GRl;->initChunkCacheSize:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->skipAudioMediaCodecStopOnRelease:Z

    iput-boolean v0, p0, LX/GRl;->enableCodecDeadlockFix:Z

    iget v0, p1, LX/FBk;->A04:I

    iput v0, p0, LX/GRl;->frequentStallIntervalThresholdMs:I

    iget v0, p1, LX/FBk;->A0D:I

    iput v0, p0, LX/GRl;->stallCountsToUpdateDynamicRebufferThreshold:I

    iget v0, p1, LX/FBk;->A03:I

    iput v0, p0, LX/GRl;->extendedMinRebufferThresholdMs:I

    const/16 v0, 0xfa0

    iput v0, p0, LX/GRl;->allowedExtendedMinRebuffePeriodMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->fixXmlParserError:Z

    const/4 v0, -0x1

    iput v0, p0, LX/GRl;->globalStallCountsToUpdateDynamicRebuffer:I

    iput v0, p0, LX/GRl;->globalStallCountsToUpdateLiveDynamicRebuffer:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableEvictPlayerOnAudioTrackInitFailed:Z

    iput-boolean v0, p0, LX/GRl;->enableCheckAudioError:Z

    const/4 v0, 0x3

    iput v0, p0, LX/GRl;->maxRetryCountByEvictPlayerOnAudioTrackInitFailed:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableEvictCacheOnExoplayerErrors:Z

    const/4 v0, 0x1

    iput v0, p0, LX/GRl;->maxRetryCountByEvictCacheOnExoplayerErrors:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->disableAudioRendererOnAudioTrackInitFailed:Z

    const/4 v0, 0x3

    iput v0, p0, LX/GRl;->audioTrackInitFailedFallbackApplyThreshold:I

    const-wide/32 v0, 0x493e0

    iput-wide v0, p0, LX/GRl;->killVideoProcessOnExoPlaybackExceptionRetryTimeMs:J

    const/4 v0, 0x3

    iput v0, p0, LX/GRl;->killVideoProcessOnExoPlaybackExceptionMaximumRetryCount:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableKillVideoProcessForAudioTrackInitFailed:Z

    iput-boolean v0, p0, LX/GRl;->enableKillVideoProcessForIllegalStateException:Z

    iput-boolean v0, p0, LX/GRl;->enableRebootDeviceErrorUIForAudioTrackInitFailed:Z

    iput-boolean v0, p0, LX/GRl;->enableRebootDeviceErrorUIForCodecInitFailed:Z

    iput-boolean v0, p0, LX/GRl;->enableRebootDeviceErrorUIForIllegalStateException:Z

    iput-boolean v0, p0, LX/GRl;->useThreadSafeStandaloneClock:Z

    iput-boolean v0, p0, LX/GRl;->useMultiPeriodBufferCalculation:Z

    iput-boolean v0, p0, LX/GRl;->isVideoQplPipelineEnabled:Z

    iput-boolean v0, p0, LX/GRl;->disableIsCachedApi:Z

    iput-boolean v0, p0, LX/GRl;->enableLoadErrorHandlingPolicy:Z

    iput-boolean v0, p0, LX/GRl;->enableBlockListingResource:Z

    iput-boolean v0, p0, LX/GRl;->enable500R1FallbackLogging:Z

    iput-boolean v0, p0, LX/GRl;->checkManifestRepresentationFormatMismatch:Z

    iput-boolean v0, p0, LX/GRl;->checkLiveSourceUri:Z

    iput-object v2, p0, LX/GRl;->oneSemanticsOsParamValue:Ljava/lang/String;

    iput-boolean v0, p0, LX/GRl;->forceOneSemanticsHandling:Z

    iput v0, p0, LX/GRl;->forceOneSemanticsWaveHandling:I

    iput v0, p0, LX/GRl;->expBackoffInRetryBaseDelay:I

    iput-boolean v0, p0, LX/GRl;->shouldLoadBinaryDataFromManifest:Z

    iput-boolean v0, p0, LX/GRl;->enhanceParseException:Z

    iput-boolean v0, p0, LX/GRl;->smartGcEnabled:Z

    iput v0, p0, LX/GRl;->smartGcTimeout:I

    iput-boolean v0, p0, LX/GRl;->getPlaybackPrefFromPrefetchRequest:Z

    iput-boolean v0, p0, LX/GRl;->useShortKey:Z

    const/4 v0, 0x3

    iput v0, p0, LX/GRl;->staleManifestThreshold:I

    iput v0, p0, LX/GRl;->staleManifestThresholdToShowInterruptUI:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->checkThumbnailCache:Z

    iput-boolean v0, p0, LX/GRl;->ignore404AfterStreamEnd:Z

    iput-boolean v0, p0, LX/GRl;->allowPredictiveAlignment:Z

    iput-boolean v0, p0, LX/GRl;->enableUnifiedGrootErrorHandling:Z

    iput v0, p0, LX/GRl;->minScoreThresholdForLL:I

    iput v0, p0, LX/GRl;->goodVsrScoreThreshold:I

    iput v0, p0, LX/GRl;->maxTrackJumpsAllowed:I

    const/4 v0, -0x1

    iput v0, p0, LX/GRl;->maxDistanceBetweenTracksMs:I

    iput v0, p0, LX/GRl;->maxPastOtherTrackDistanceMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableVideoDebugEventLogging:Z

    iput-boolean v0, p0, LX/GRl;->respectDroppedQualityFlag:Z

    iput-object v2, p0, LX/GRl;->ssAbrExperimentSetting:Ljava/lang/String;

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->ssAbrAlphaDecay:F

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->ssAbrNumSamplesAvg:I

    iput v0, p0, LX/GRl;->ssAbrMinSamples:I

    iput-boolean v0, p0, LX/GRl;->enableJumpTrackFallingBehind:Z

    iput-boolean v0, p0, LX/GRl;->enable404SegmentRemapping:Z

    iput-boolean v0, p0, LX/GRl;->enableOneSemanticsLoaderRetry:Z

    iput-boolean v0, p0, LX/GRl;->enable204SegmentRemapping:Z

    const/4 v0, 0x3

    iput v0, p0, LX/GRl;->maxPredictedSegmentsToRemap:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->skipThumbnailCacheKey:Z

    iput-boolean v0, p0, LX/GRl;->enableCreateByteBufferFromABufferNullCheckHooks:Z

    iput-boolean v0, p0, LX/GRl;->enableBusySignalToFramework:Z

    iput-boolean v0, p0, LX/GRl;->shouldWarmupAwareOfAppScrolling:Z

    iput-boolean v0, p0, LX/GRl;->shouldUseWarmupSlot:Z

    iput-boolean v0, p0, LX/GRl;->enableDelayWarmupRunning:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/GRl;->delayWarmupRunningMs:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableWarmupProcessPeriodically:Z

    iput-boolean v0, p0, LX/GRl;->enableStopWarmupSchedulerEmpty:Z

    iput-boolean v0, p0, LX/GRl;->enableFillBufferHooks:Z

    iput-boolean v0, p0, LX/GRl;->enableFreeNodeHooks:Z

    iput-boolean v0, p0, LX/GRl;->enableOnMessageReceivedHooks:Z

    iput-boolean v0, p0, LX/GRl;->enableSendCommandHooks:Z

    iput-boolean v0, p0, LX/GRl;->enableOnOMXEmptyBufferDoneHooks:Z

    iput-boolean v0, p0, LX/GRl;->enableFillFreeBufferCheckNodeHooks:Z

    iput-boolean v0, p0, LX/GRl;->enableFixRemovePlayerViewFromParent:Z

    iput-boolean v0, p0, LX/GRl;->latencyControllerBypassLimits:Z

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/GRl;->targetBufferBytesFactor:F

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/GRl;->enableOverrideBufferWatermark:Z

    iput-boolean v1, p0, LX/GRl;->enableOverrideEndPosition:Z

    iget-object v0, p1, LX/FBk;->A0Q:LX/GRH;

    iput-object v0, p0, LX/GRl;->loggerSDKConfig:LX/GRH;

    iput-boolean v1, p0, LX/GRl;->enableMp4MultiTrafBoxesFix:Z

    const/4 v0, 0x5

    iput v0, p0, LX/GRl;->chunkSourceRetryMaximum:I

    iget-object v0, p1, LX/FBk;->A0X:Ljava/util/Map;

    iput-object v0, p0, LX/GRl;->liveLatencySettings:Ljava/util/Map;

    iput-boolean v1, p0, LX/GRl;->forceDisableULL:Z

    iput v1, p0, LX/GRl;->bufferDecreaseTimeMs:I

    iput v1, p0, LX/GRl;->scalingBufferErrorMs:I

    const/16 v0, 0xc8

    iput v0, p0, LX/GRl;->timeBetweenPIDSamplesMs:I

    iput v0, p0, LX/GRl;->adjustSpeedBottomThresholdMs:I

    const/16 v0, 0x32

    iput v0, p0, LX/GRl;->desiredBufferAcceptableErrorMs:I

    iput-boolean v1, p0, LX/GRl;->disableSpeedAdjustmentOnBadUserExperience:Z

    const/16 v0, 0x12c

    iput v0, p0, LX/GRl;->adjustSpeedTopThresholdMs:I

    iput-boolean v1, p0, LX/GRl;->enableRetryErrorLoggingInCancel:Z

    iput-boolean v1, p0, LX/GRl;->enableRetryOnConnection:Z

    iput-boolean v1, p0, LX/GRl;->enableLoaderRetryLoggingForManifest:Z

    iput-boolean v1, p0, LX/GRl;->enableLoaderRetryLoggingForMedia:Z

    iput-boolean v1, p0, LX/GRl;->enableContinueLoadingLoggingForManifest:Z

    iput-boolean v1, p0, LX/GRl;->enableContinueLoadingLoggingForMedia:Z

    iput-boolean v1, p0, LX/GRl;->disableLoadingRetryOnFatalError:Z

    const/4 v0, 0x1

    iput v0, p0, LX/GRl;->errorRecoveryAttemptRepeatCountFlushThreshold:I

    iput-boolean v1, p0, LX/GRl;->disableNetworkErrorCountInChunkSource:Z

    iput-boolean v1, p0, LX/GRl;->ignoreEmptyProfileLevels:Z

    iput-boolean v1, p0, LX/GRl;->exceedRendererCapabilitiesIfAllFilteredOut:Z

    iput-boolean v1, p0, LX/GRl;->alwaysPrefetchInBgDefaultPriorityThread:Z

    iput-boolean v1, p0, LX/GRl;->alwaysPrefetchInIdleExecutor:Z

    iput-boolean v1, p0, LX/GRl;->enableCustomizedPrefetchThreadPriority:Z

    iput v1, p0, LX/GRl;->customizedPrefetchThreadPriority:I

    iput-boolean v0, p0, LX/GRl;->postStoriesGrootPrefetchToHeroManagerThread:Z

    iput-boolean v0, p0, LX/GRl;->cleanUpHeartbeatMessagesIfNotPlaying:Z

    iput-boolean v0, p0, LX/GRl;->cleanUpHeartbeatMessagesOnStall:Z

    iput-boolean v0, p0, LX/GRl;->cleanUpHeartbeatMessagesOnPause:Z

    iget-boolean v0, p1, LX/FBk;->A0g:Z

    iput-boolean v0, p0, LX/GRl;->enableDynamicMinRebufferMsController:Z

    iput-boolean v1, p0, LX/GRl;->enableGlobalStallMonitor:Z

    iput-boolean v1, p0, LX/GRl;->enableGlobalNetworkMonitor:Z

    iput-boolean v1, p0, LX/GRl;->enableLiveTierSpecificBufferSetting:Z

    const/4 v0, -0x1

    iput v0, p0, LX/GRl;->liveMinRetryCounts:I

    const/4 v0, 0x5

    iput v0, p0, LX/GRl;->prefetchThreadUpdatedPriority:I

    iput-boolean v1, p0, LX/GRl;->changeThreadPriorityForPrefetch:Z

    const/4 v0, -0x1

    iput v0, p0, LX/GRl;->numOfBytesBeforeLoaderThreadSleep:I

    iput-boolean v1, p0, LX/GRl;->enableLiveBroadcastErrorUI:Z

    iput-boolean v1, p0, LX/GRl;->enableFixTrackIndexOOB:Z

    iput-boolean v1, p0, LX/GRl;->shouldAlwaysDo503Retry:Z

    iput v0, p0, LX/GRl;->retryCountsForStartPlayManifestFetch:I

    iput v0, p0, LX/GRl;->retryCountsForStartPlayManifest503:I

    iput-boolean v1, p0, LX/GRl;->enableHttpPriorityForPrefetch:Z

    iput-boolean v1, p0, LX/GRl;->enableHttpPriorityForStreaming:Z

    iput-boolean v1, p0, LX/GRl;->useHttpPriorityIncrementalForStreaming:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->useHttpPriorityIncrementalForPrefetch:Z

    iput-boolean v0, p0, LX/GRl;->useHttpPriorityIncrementalForLongBufferedStreaming:Z

    iput-boolean v1, p0, LX/GRl;->useHttpPriorityWarmupForLongBufferedStreaming:Z

    iput-boolean v1, p0, LX/GRl;->useNetworkAwareHttpPriorityIncrementalForStreaming:Z

    iput-boolean v1, p0, LX/GRl;->useLowPriorityForSecondPhasePrefetch:Z

    iput v1, p0, LX/GRl;->bufferedDurationBasedHttpPriorityUpperBoundMs:I

    iput v1, p0, LX/GRl;->bufferedDurationBasedHttpPriorityLowerBoundMs:I

    const/high16 v0, -0x40800000    # -1.0f

    iput v0, p0, LX/GRl;->watchTimeThresholdToDisableSecondPhasePrefetchSeconds:F

    iput-boolean v1, p0, LX/GRl;->changePriorityForPrefetchRequestOnPlayerStart:Z

    iput-boolean v1, p0, LX/GRl;->useLowerHttpPriorityForUnimportantPrefetch:Z

    iput-boolean v1, p0, LX/GRl;->useLowerHttpPriorityForAllPrefetch:Z

    iput-boolean v1, p0, LX/GRl;->useOutputSurfaceWorkaround:Z

    iput-boolean v1, p0, LX/GRl;->enableBufferAwareJumpSeek:Z

    iput v1, p0, LX/GRl;->jumpSeekPosLeftoverBufferDurationMs:I

    iput v1, p0, LX/GRl;->jumpSeekReductionFactorPct:I

    iput-boolean v1, p0, LX/GRl;->enableBackwardJumpSeekKeyframeSync:Z

    iput v1, p0, LX/GRl;->seekParameterOptionIndex:I

    iput-boolean v1, p0, LX/GRl;->skipAV1PreviousKeyFrameSeek:Z

    iput-boolean v1, p0, LX/GRl;->enableCacheLookUp:Z

    iput-boolean v1, p0, LX/GRl;->usePerVideoLookupToCheckCache:Z

    iput-boolean v1, p0, LX/GRl;->useIsCachedSkipInit:Z

    iput-boolean v1, p0, LX/GRl;->releaseHeroManagerWhenLowMemInBg:Z

    iput-boolean v1, p0, LX/GRl;->useAdAwareLoadControl:Z

    const v0, 0x3e99999a

    iput v0, p0, LX/GRl;->huddleLatencyMaxSpeedDelta:F

    iput-boolean v1, p0, LX/GRl;->enablePIDForHuddle:Z

    iput-boolean v1, p0, LX/GRl;->forceStereoToMonoConversion:Z

    iput-boolean v1, p0, LX/GRl;->enableQuickDashPlayback:Z

    iput-boolean v1, p0, LX/GRl;->enableClockSync:Z

    iput-boolean v1, p0, LX/GRl;->enableStreamLatencyToggleOverride:Z

    iput v1, p0, LX/GRl;->streamLatencyToggleStateOverride:I

    const/16 v0, 0xbb8

    iput v0, p0, LX/GRl;->streamLatencyTogglePIDDesiredBufferMs:I

    const v0, 0x1d4c0

    iput v0, p0, LX/GRl;->streamLatencyTogglePIDIntegralBoundMs:I

    const v0, 0x3e99999a

    iput v0, p0, LX/GRl;->streamLatencyToggleMaxSpeedDelta:F

    const/high16 v0, 0x40000000    # 2.0f

    iput v0, p0, LX/GRl;->streamLatencyToggleSpeedUpBandwidthMultiplier:F

    iput-boolean v1, p0, LX/GRl;->includePlaybackSessionIdHeader:Z

    iput-boolean v1, p0, LX/GRl;->enableE2ECDNTracing:Z

    iput-boolean v1, p0, LX/GRl;->enablePredictedUrlTracing:Z

    iput-object v2, p0, LX/GRl;->broadcasterIdAllowlist:Ljava/lang/String;

    iput-object v2, p0, LX/GRl;->playerOriginPausedLoadingBlackList:Ljava/lang/String;

    iget-object v0, p1, LX/FBk;->A0Z:Ljava/util/Set;

    iput-object v0, p0, LX/GRl;->pausedLoadingTriggerTypes:Ljava/util/Set;

    iget-object v0, p1, LX/FBk;->A0Y:Ljava/util/Set;

    iput-object v0, p0, LX/GRl;->originAllowlistForAlternateCodec:Ljava/util/Set;

    iget-object v0, p1, LX/FBk;->A0d:Ljava/util/Set;

    iput-object v0, p0, LX/GRl;->wakelockOriginLists:Ljava/util/Set;

    iput-boolean v1, p0, LX/GRl;->enableExcessiveNumUriRedirectLogging:Z

    iput v1, p0, LX/GRl;->excessiveUriRedirectLoggingLimit:I

    iput-boolean v1, p0, LX/GRl;->enableVodPausedLoading:Z

    iput v1, p0, LX/GRl;->maxBufferToDownloadInPausedLoadingMs:I

    iput v1, p0, LX/GRl;->maxTimeAllowedSpentInPausedLoadingMs:I

    iput-boolean v1, p0, LX/GRl;->enableLastPlaybackSpeedCacheUpdate:Z

    iput-boolean v1, p0, LX/GRl;->enableIsTextAdaptationSetNotFoundLogging:Z

    iput-boolean v1, p0, LX/GRl;->enableOffloadInitHeroService:Z

    iput-boolean v1, p0, LX/GRl;->enableBackgroundServicePlayerReuse:Z

    iput-boolean v1, p0, LX/GRl;->useMinIntentBasedWatermarkBeforePlay:Z

    iput-boolean v1, p0, LX/GRl;->enableMediaSessionControls:Z

    iput-boolean v1, p0, LX/GRl;->enableRequestAnalyticsTagsHeaderLogging:Z

    iput-boolean v1, p0, LX/GRl;->disableTextRendererOn404LoadError:Z

    iput-boolean v1, p0, LX/GRl;->useFallbackLogging:Z

    iput-boolean v1, p0, LX/GRl;->disableTextRendererOn404InitSegmentLoadError:Z

    iput-boolean v1, p0, LX/GRl;->disableTextRendererOn500LoadError:Z

    iput-boolean v1, p0, LX/GRl;->disableTextRendererOn500InitSegmentLoadError:Z

    iput-boolean v1, p0, LX/GRl;->enableVideoPlayerServerSideBweAnnotations:Z

    iput-boolean v1, p0, LX/GRl;->enableUnexpectedExoExceptionLogging:Z

    iput-boolean v1, p0, LX/GRl;->enableEmsgTrackForAll:Z

    iput-boolean v1, p0, LX/GRl;->enableInstreamAdsEmsgLog:Z

    iput v1, p0, LX/GRl;->audioStallCountThresholdMs:I

    iput-boolean v1, p0, LX/GRl;->enableVideoPositionLoggingInCompleteEvent:Z

    iput-boolean v1, p0, LX/GRl;->surfaceMPDFailoverImmediately:Z

    iput-boolean v1, p0, LX/GRl;->disableTextTrackOnMissingTextTrack:Z

    iput-boolean v1, p0, LX/GRl;->enableTextTrackWithKnownLanguage:Z

    iput v1, p0, LX/GRl;->numDashChunkMemoryCacheSampleStreams:I

    iput-boolean v1, p0, LX/GRl;->disableTextEraLoggingOnLoadRetry:Z

    iget-object v0, p1, LX/FBk;->A0R:LX/GRA;

    iput-object v0, p0, LX/GRl;->tslogSettings:LX/GRA;

    iput-boolean v1, p0, LX/GRl;->dontRetry403OnExpiredUrl:Z

    iput-boolean v1, p0, LX/GRl;->useFullscreenTransitionPrediction:Z

    const-wide/16 v0, 0x7d0

    iput-wide v0, p0, LX/GRl;->fullscreenPredictionRequestTimeoutMs:J

    const/4 v0, -0x1

    iput v0, p0, LX/GRl;->maxAllowed503RetryCount:I

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/GRl;->advanceSegmentOnNetworkErrors:J

    iput-wide v0, p0, LX/GRl;->maxSegmentsToAdvance:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableExplicitTextDataSourceCreation:Z

    iput-boolean v0, p0, LX/GRl;->disableLiveCaptioningOnPlayerInit:Z

    iput-boolean v0, p0, LX/GRl;->enableVrlQplLoggingEvents:Z

    iput-boolean v0, p0, LX/GRl;->reduceMemoryDataSinkMemorySpike:Z

    iput-boolean v0, p0, LX/GRl;->useExoPlayerBuilder:Z

    iput-boolean v0, p0, LX/GRl;->exoPlayerUpgrade218verifyApplicationThread:Z

    iput-boolean v0, p0, LX/GRl;->enable416Logging:Z

    iput-boolean v0, p0, LX/GRl;->enableVodContentLengthLogging:Z

    iput-boolean v0, p0, LX/GRl;->enableServerSideForwardTracing:Z

    iput-boolean v0, p0, LX/GRl;->enableMixedCodecManifestSupport:Z

    iput-boolean v0, p0, LX/GRl;->respectAbrForUll:Z

    iput-boolean v0, p0, LX/GRl;->respectAbrIndexForUll:Z

    iput-boolean v0, p0, LX/GRl;->disableUllBasedOnHoldout:Z

    iput-boolean v0, p0, LX/GRl;->enableWifiLockManager:Z

    iput-boolean v0, p0, LX/GRl;->enableClearStallOnBroadcastEnd:Z

    iput-boolean v0, p0, LX/GRl;->enableSecondaryChannelLoggingForLite:Z

    iput-boolean v0, p0, LX/GRl;->enableDav1dAsMediaCodecAdapter:Z

    iput-boolean v0, p0, LX/GRl;->enableDav1dOpenGLRendering:Z

    iput v0, p0, LX/GRl;->secondaryChannelLoggingMaxNumOfFramesInOneJson:I

    iput v0, p0, LX/GRl;->secondaryChannelLoggingMaxDisplayedFramesStringSize:I

    iput v0, p0, LX/GRl;->secondaryChannelLoggingSamplingFactor:I

    iput-boolean v0, p0, LX/GRl;->surfaceControlForceVideoSizeUpdate:Z

    iput-boolean v0, p0, LX/GRl;->forceAdjustSurfaceOnMainThread:Z

    iput-boolean v0, p0, LX/GRl;->disableVideoTrackForInVisibleVDD:Z

    iput-boolean v0, p0, LX/GRl;->shouldDisableAV1VideoTrackOnlyforVDD:Z

    iput-boolean v0, p0, LX/GRl;->useInterruptedIoException:Z

    iput-boolean v0, p0, LX/GRl;->enableMixeCodecManifestLogging:Z

    iput-boolean v0, p0, LX/GRl;->enableMixeCodecManifestVideoCodecSwitchedLogging:Z

    iput-boolean v0, p0, LX/GRl;->enablePCMBufferListener:Z

    iput-boolean v0, p0, LX/GRl;->enableLoggingEmptyOrNullVideoId:Z

    iput-boolean v0, p0, LX/GRl;->enableDav1dOpenGLIncorrectSurfaceSizeFix:Z

    iput-boolean v0, p0, LX/GRl;->useBufferedCacheDataSink:Z

    iput-boolean v0, p0, LX/GRl;->useHandlerThreadPool:Z

    iput-boolean v0, p0, LX/GRl;->useMainThreadForHeroPlayer:Z

    const/4 v0, 0x4

    iput v0, p0, LX/GRl;->handlerThreadPoolSize:I

    const/4 v0, 0x0

    iput v0, p0, LX/GRl;->bufferedCacheDataSinkSize:I

    iput-boolean v0, p0, LX/GRl;->enableAV1SRShader:Z

    const/16 v0, 0x3e8

    iput v0, p0, LX/GRl;->maxWidthForAV1SRShader:I

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableSaturation:Z

    const/high16 v0, 0x3f800000    # 1.0f

    iput v0, p0, LX/GRl;->saturationFactor:F

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableAdditionalDecoderInitFailureMessage:Z

    iput-boolean v0, p0, LX/GRl;->enableFixForOnPreparingCallback:Z

    iput-boolean v0, p0, LX/GRl;->enableOpenGLSurfaceSizeUpdateFix:Z

    iput-object v2, p0, LX/GRl;->prefetchSubOriginBlockList:Ljava/lang/String;

    iput-boolean v0, p0, LX/GRl;->enforceSizeLimitOnSecondPhasePrefetch:Z

    iput-boolean v0, p0, LX/GRl;->attachGrootPlayerListenerWhenUsingSurfaceControl:Z

    iput-boolean v0, p0, LX/GRl;->resizeAndRepositionGrootSurfaceControl:Z

    iput-boolean v0, p0, LX/GRl;->preventAdjustWhenSurfaceNotValid:Z

    iput v0, p0, LX/GRl;->forceManifestFilteringMode:I

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->enableDav1dOpenGLRenderingHandleAspectRatio:Z

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableMpdFilteringUtils:Z

    iput-boolean v0, p0, LX/GRl;->enableTransferListenerCallbackPerfFix:Z

    iput-boolean v0, p0, LX/GRl;->enableDynamicPrefetchCacheFileSize:Z

    iput-boolean v0, p0, LX/GRl;->enableDynamicPrefetchCacheFileSizePrefetchOnly:Z

    const-wide/16 v0, 0x0

    iput-wide v0, p0, LX/GRl;->minCacheFileSizeForDynamicChunkingInBytes:J

    const/4 v0, 0x0

    iput-boolean v0, p0, LX/GRl;->enableDashManifestPool:Z

    iput v0, p0, LX/GRl;->dashManifestPoolSize:I

    iput-boolean v0, p0, LX/GRl;->disablePoolingForDav1dMediaCodec:Z

    iput-boolean v0, p0, LX/GRl;->useBackgroundHandlerForHeroLiveManager:Z

    iput-boolean v0, p0, LX/GRl;->useAllSettingsToSupportLowerLatency:Z

    iput-boolean v0, p0, LX/GRl;->combineInitFirstSegment:Z

    const/4 v0, 0x1

    iput-boolean v0, p0, LX/GRl;->fixNullCacheSpan:Z

    const/4 v1, 0x0

    iput-boolean v1, p0, LX/GRl;->enableAudioTrackRetry:Z

    iput v1, p0, LX/GRl;->playbackAboutToFinishCallbackTriggeringRemainingDuration:I

    iget-boolean v0, p1, LX/FBk;->A0j:Z

    iput-boolean v0, p0, LX/GRl;->shouldAddDefaultMP4Extractor:Z

    iput-boolean v1, p0, LX/GRl;->quitHandlerSafely:Z

    iget-boolean v0, p1, LX/FBk;->A0k:Z

    iput-boolean v0, p0, LX/GRl;->shouldCleanupHeroManagerThread:Z

    iput-boolean v1, p0, LX/GRl;->enableCodecHistoryOverlayField:Z

    iput-boolean v1, p0, LX/GRl;->appendReconfigurationDataForDrmContentFix:Z

    iget v0, p1, LX/FBk;->A0C:I

    iput v0, p0, LX/GRl;->sdkVersionToUseDefaultLoadControl:I

    iget v0, p1, LX/FBk;->A0B:I

    iput v0, p0, LX/GRl;->sdkVersionToUseConservativeLoadControl:I

    iget v0, p1, LX/FBk;->A08:I

    iput v0, p0, LX/GRl;->sdKVersionToUseCustomizedBuffering:I

    iget v0, p1, LX/FBk;->A09:I

    iput v0, p0, LX/GRl;->sdKVersionToUseTargetBufferOverwrite:I

    iget v0, p1, LX/FBk;->A06:I

    iput v0, p0, LX/GRl;->minCustomizedWABufferMs:I

    iget v0, p1, LX/FBk;->A0E:I

    iput v0, p0, LX/GRl;->targetBytesForOverwrite:I

    iget v0, p1, LX/FBk;->A05:I

    iput v0, p0, LX/GRl;->maxCustomizedWABufferMs:I

    iget v0, p1, LX/FBk;->A00:I

    iput v0, p0, LX/GRl;->customizedWABufferForPlaybackMs:I

    iget v0, p1, LX/FBk;->A02:I

    iput v0, p0, LX/GRl;->customizedWARebufferMs:I

    iget v0, p1, LX/FBk;->A01:I

    iput v0, p0, LX/GRl;->customizedWAIndividualAllocationSize:I

    iget-boolean v0, p1, LX/FBk;->A0h:Z

    iput-boolean v0, p0, LX/GRl;->enableHeroPlayerMaxLoopCount:Z

    iget-boolean v0, p1, LX/FBk;->A0e:Z

    iput-boolean v0, p0, LX/GRl;->allowRequestForSoftwareDecoder:Z

    iput-boolean v1, p0, LX/GRl;->useDefaultTrackSelector:Z

    iget v0, p1, LX/FBk;->A0A:I

    iput v0, p0, LX/GRl;->sdkVersionToBypassHeroStateRefresh:I

    iget-boolean v0, p1, LX/FBk;->A0m:Z

    iput-boolean v0, p0, LX/GRl;->useWAPlayerPoolLoadControl:Z

    iget v0, p1, LX/FBk;->A0F:I

    iput v0, p0, LX/GRl;->threadSleepMsForDecoderInitFailure:I

    return-void
.end method
